### ISSUE TITLE
Unable to exclude aws-sdk from bundle

### ISSUE THREAD

**Issue by C5H8NNaO4** [serverless-heaven/serverless-webpack#1222]
# This is a (Bug Report / Feature Proposal)

## Description

For bug reports:
* The aws-sdk package gets bundled into the lambda.zip bundle
* The aws-sdk should not be bundled
* The config used is as follows:
```
webpack:
    webpackConfig: ./webpack.config.js
    includeModules:
        forceExclude:
            - aws-sdk
####
webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    excludeFiles: node_modules/aws-sdk/**
```

The aws-sdk has also been added as an external in the webpack config. 

However the aws-sdk is still being included in the bundle. 

Running a script  like `rm node_modules/aws-sdk` unfortunately throws an error. So I can't use that as a workaround.

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.8.0
* ***Webpack version you're using***: 5.74.0
* ***Serverless Framework Version you're using***: ??
* ***Operating System***: Windows

**Comment by vicary** [comment]
Would you mind try adding an exclude pattern in `package`?

### serverless.yml
```yml
package:
  patterns:
    - '!node_modeuls/aws-sdk/**'
```
