### ISSUE TITLE
Allow glob or regex strings for forceExclude option

### ISSUE THREAD

**Issue by rizowski** [serverless-heaven/serverless-webpack#1348]
# Feature Proposal

## Description

Allow setting a glob pattern for forceExclude so we can exclude an entire namespaced package.

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

Moving onto Node 18 and fully trying to use `@aws-sdk/*@V3` in the AWS lambda environment I need to exclude the entire `@aws-sdk/*` namespace to utilize the package installed in the environment. We've been blocked from fully migrating to the V3 package because `serverless-webpack` isn't excluding the entire lib like it does with `aws-sdk` v2. Even though `@aws-sdk` v3 is "modular" they still bring in a lot of their own @aws-sdk/@v3 as subdependencies.

Beyond that example, using lambda layers could also create a similar issue when bundling specific dependencies and publishing those independently of the main application. If those are namespaced, we can have the same problem.

* If there is additional config how would it look

Glob:
```
custom:
  webpack:
    includeModules:
      forceExclude:
        - "@aws-sdk/*"
```

Regex:
```
custom:
  webpack:
    includeModules:
      forceExclude:
        - "^@aws-sdk"
```

Similar or dependent issue(s):
AFIK no one has requested it explicitly

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.11.0
* ***Webpack version you're using***: 5.75.0
* ***Serverless Framework Version you're using***: 3.25.1
* ***Operating System***: Mac OS 13.1
* ***Stack Trace (if available)***:
