### ISSUE TITLE
Runtime.ImportModuleError: Error: Cannot find module '@babel/runtime-corejs3/core-js-stable/instance/map'

### ISSUE THREAD

**Issue by juztinlazaro** [serverless-heaven/serverless-webpack#1650]
![image](https://github.com/serverless-heaven/serverless-webpack/assets/10995629/5666ca75-c435-4f5d-b674-4365c00b3865)

## Additional Data

* ***Serverless-Webpack Version you're using***: `"serverless-webpack": "5.3.0",`
* ***Webpack version you're using***: `"webpack": "5.81.0",`
* ***Serverless Framework Version you're using***: `"serverless": "3.36.0",`
* ***Operating System***:
* ***Stack Trace (if available)***:

**Comment by juztinlazaro** [comment]
up

**Comment by j0k3r** [comment]
Well, what can we do?
Do you think the problem is cristal clear for us and we could provide a direct fix? No.
We need a lot of more information you removed from the default template.

Also, we might need to see some source code to understand the problem.
Without that, we really can't help you.

**Comment by juztinlazaro** [comment]
Hi @j0k3r just update the details thanks

**Comment by juztinlazaro** [comment]
for some reason i need to forceInclude the dependencies

```
webpack:
  webpackConfig: serverless_v3/webpack.config.js
  includeModules:
    forceInclude:
      - lodash
      - moment
      - es6-promisify
  packager: 'yarn'
  concurrency: 5 # desired concurrency, defaults to the number of available cores
  serializedCompile: true # backward compatible, this translates to concurrency: 1
```
