### ISSUE TITLE
.d.ts not recognize in serverless-webpack typescript

### ISSUE THREAD

**Issue by juztinlazaro** [serverless-heaven/serverless-webpack#1685]
.d.ts not recognize in serverless-webpack typescript

![image](https://github.com/serverless-heaven/serverless-webpack/assets/10995629/c975f8f2-0865-44dc-86f9-f4682682d399)

![image](https://github.com/serverless-heaven/serverless-webpack/assets/10995629/380d9b5d-91ca-49fd-8187-afd3be9a9595)

serverless
```
service: my-insure-serverless
frameworkVersion: ">=1.25.0"

plugins:
  - serverless-webpack
  - serverless-offline-aws-ssm
  - serverless-offline
  - serverless-domain-manager
  - serverless-plugin-provider-groups
  - serverless-plugin-warmup

customs:
serverless-offline:
    port: 3003

  webpack:
    webpackConfig: './serverless/webpack.config.js'
    packager: 'yarn'
    includeModules: true
```

webpack:
```
const path = require('path');
const nodeExternals = require('webpack-node-externals');
const slsw = require('serverless-webpack');
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');

const isLocal = slsw.lib.webpack.isLocal;

module.exports = {
  mode: isLocal ? 'development' : 'production',
  entry: slsw.lib.entries,
  externals: [nodeExternals()],
  devtool: 'source-map',
  resolve: {
    extensions: ['.js', '.jsx', '.json', '.ts', '.tsx'],
  },
  output: {
    libraryTarget: 'commonjs2',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js',
  },
  target: 'node',
  cache: {
    type: 'filesystem',
    allowCollectingMemory: true,
    cacheDirectory: path.resolve('.webpackCache'),
  },
  module: {
    rules: [
      {
        // Include ts, tsx, js, and jsx files.
        test: /\.(ts|js)x?$/,
        exclude: /node_modules/,
        use: ['babel-loader'],
      },
    ],
  },
  plugins: [new ForkTsCheckerWebpackPlugin()],
};

```

tsconfig: 
```
{
  "compilerOptions": {
    "sourceMap": true,
    "target": "es6",
    "allowJs": true, 
    "jsx": "react",
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "declaration": false,
    "removeComments": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "allowSyntheticDefaultImports": true,
    "preserveSymlinks": true,
    "isolatedModules": true,
    "strict": true,
    "outDir": ".build",
    "baseUrl": "./",
    "paths" : {
      "*" : ["client/*", "serverless/*"]
    },
    "lib": [
      "es6",
      "es7",
      "dom"
    ],
    "typeRoots": ["serverless/types", "node_modules/@types"],
    "types": [
      "jest",
      "node",
      // need to define each declaration due to this issue
      // https://github.com/prisma-labs/serverless-plugin-typescript/issues/92
      "./serverless/types/dynamic",
      "./serverless/types/models",
      "./serverless/types/models/BlackFinModel",
      "./serverless/types/models/UIModel",
      "./serverless/types/models/FactFindModel",
      "./serverless/types/otherLibs"
    ],
  },
  "exclude": [
    "node_modules",
    "serverless/test",
    "serverless/types"
  ]
}
```
