### ISSUE TITLE
serverless-webpack running webpack on lambda containers with `image.name` property

### ISSUE THREAD

**Issue by ilyesBen** [serverless-heaven/serverless-webpack#1884]
# This is a Bug Report 

## Description

For bug reports:
* What went wrong?
serverless-webpack is not ignoring lambda containers when they have `image.name` property. They are only ignored if the `image.uri` property is used.

* What did you expect should have happened?
It should not try to deploy the lambda container as it does not have the `handler` property and has the `image` property.

* What was the config you used?

```
service: converter

frameworkVersion: '3'

plugins:
  - serverless-webpack

custom:
  webpack:
    packager: yarn
    includeModules: true
    individually: true

provider:
  name: aws
  region: eu-west-2
  runtime: nodejs20.x
  memorySize: 1024
  timeout: 120
  ecr:
    images:
      docx_convert_image:
        path: ./

functions:
  pdfToImageConverter:
    handler: src/functions/pdfToImageConverter.handler
    name: pdfToImageConverter-${sls:stage}
  
  docxToImageConverter:
    name: docxToImageConverter-${sls:stage}
    architecture: x86_64
    image:
      name: docx_convert_image
      command: 
        - docxToImageConverter.handler
```

* What stacktrace or error message from your provider did you see?

```
✖ Stack converter-dev failed to deploy (0s)
Environment: darwin, node 18.19.0, framework 3.38.0 (local) 3.36.0v (global), plugin 7.2.3, SDK 4.5.1
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
No matching handler found for 'docxToImageConverter' in '/Users/ilyesben/Desktop/Atlas/converter-service'. Check your service definition.
```

Similar or dependent issue(s):
#825 

## Additional Data

* ***Serverless-Webpack Version you're using***: `5.5.5`
* ***Webpack version you're using***: `5.91.0`
* ***Serverless Framework Version you're using***: `3.38.0`
* ***Operating System***: `macOS`
* ***Stack Trace (if available)***:
