### ISSUE TITLE
include/exclude not working (trying to include a binary with a function)

### ISSUE THREAD

**Issue by bastibense** [serverless-heaven/serverless-webpack#242]
# This is a Bug Report

## Description
Started with the `aws-nodejs-typescript` template. 

I'm trying to include an executable/binary with the function package, so it can be executed on Lambda to do some work there. The binary would be called from within the function as you'd normally call command line binaries on linux.

I tried different variants of include/exclude config params, set individually to false and other tweaks to get the generated package/lambda function to include the binary, but without success.

Am I doing something wrong here, or is it a bug?

## serverless.yml

```
service:
  name: myservice

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  memorySize: 1024
  stage: dev


functions:

  processInputFile:
    handler: input-processor/handler.hello
    package:
      include:
        - bin/procbinary
    events:
      - http:
          method: get
          path: render-pdf
```

## File Layout

* input-processor
  * bin
    * procbinary (my custom executable)
* node_modules
* tsconfig.json
* webpack.config.js
* package.json
* serverless.yml

## Additional Data

* ***Serverless-Webpack Version you're using***: 3.1.0
* ***Webpack version you're using***: 3.6.0
* ***Serverless Framework Version you're using***: 1.23.0
* ***Operating System***: macOS 10.12.6 (16G29)
