### ISSUE TITLE
Error due to missing files in .webpack/service

### ISSUE THREAD

**Issue by MandyJCho** [serverless-heaven/serverless-webpack#287]
# This is a Bug Report

## Description
Running sls command with either with webpack, deploy, or package consistently fails due to a different missing file each time in .webpack/service when certain externals are included. 

Here is one of the errors I'm getting from running `sls webpack` whenever I add any externals

```
Error --------------------------------------------------

  ENOENT: no such file or directory, unlink 'project/.webpack/service/node_modules/base64-js/README.md'

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: ENOENT: no such file or directory, unlink 'project/.webpack/service/node_modules/base64-js/README.md'
    at Error (native)
From previous event:
    at PluginManager.invoke (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:366:22)
    at PluginManager.spawn (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:384:17)
    at ServerlessWebpack.BbPromise.bind.then.then.then project/node_modules/serverless-webpack/index.js:113:51)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

```

Here are my configurations

webpack.config.js

```
const slsw = require('serverless-webpack');
const nodeExternals = require('webpack-node-externals');
const path = require('path');

module.exports = {
  entry: slsw.lib.entries,
  target: 'node',
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /(node_modules|bower_components)/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['env']
          }
        }
      },
      {
        test: /\.(graph|g)ql$/,
        exclude: /node_modules/,
        use: [
          {
            loader: 'graphql-tag/loader'
          }
        ]
      }
    ]
  },
  output: {
    libraryTarget: 'commonjs',
    path: path.resolve('.webpack'),
    filename: 'src/handler.js'
  },
  externals: [nodeExternals()]
};
```

serverless.yml

```
service: server

provider:
  name: aws
  runtime: nodejs6.10
  profile: reactive
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:DescribeStream
        - dynamodb:ListStreams
      Resource: arn:aws:dynamodb:us-east-1:*:*

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack

custom:
  dotenv:
    path: configs/.env
    include:
      - AWS_USER_ARN
  webpack: ./webpack.config.js
  webpackIncludeModules: true

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          method: get
          path: hello

  graphql:
      handler: src/handler.graphqlHandler
      events:
      - http:
          path: graphql
          method: post
          cors: true
  playground:
    handler: src/handler.playgroundHandler
    events:
    - http:
        path: playground
        method: get
        cors: true
  graphiql:
    handler: src/handler.graphiqlHandler
    events:
    - http:
        path: graphiql
        method: get
        cors: true

resources: .... 
```

## Additional Data

* ***Serverless-Webpack Version you're using***: 4.0.0
* ***Webpack version you're using***: 3.6.0
* ***Serverless Framework Version you're using***: 1.24.1
* ***Operating System***: Windows10
