### ISSUE TITLE
How to deal with obscure cloudwatch logs? 

### ISSUE THREAD

**Issue by tommedema** [serverless-heaven/serverless-webpack#291]
I'm creating a custom resource that is backed by a serverless lambda function, which is packaged by `serverless-webpack`. A simplified version of the `serverless.yml` file looks like:

```
frameworkVersion: '=1.24.1'

service: ${{file(./package.json):name}}

plugins:
  # transpile functions' ES7 to ES5 for provider runtime compatibility
  - serverless-webpack
  
package:
  individually: true
        
custom:
  ...
  
  # allows for the exclusion of external modules to webpack
  webpackIncludeModules: true
    
provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 512
  timeout: 10
  stage: ${{opt:stage, 'dev'}}
  region: ${{opt:region, 'eu-west-2'}}
  variableSyntax: "\\${{([ ~:a-zA-Z0-9._\\'\",\\-\\/\\(\\)]+?)}}" # use ${{}} to access serverless variables
      
functions:
  # special function backing custom resource to generate SSL certificates
  requestCertificate:
    handler: scripts/request-certificate.handler
  
   ...
          
resources:
  Conditions:
    ...
   
  Resources:
    
    # custom resource to retrieve SSL certificates
    CertificateResource:
      Condition: ShouldRequestCertificate
      Type: Custom::CertificateResource
      Properties:
        # a UUID forces a refetch from lambda on eacha deploy
        UUID: ${{file(./scripts/uuid.js)}}
        ServiceToken:
          Fn::GetAtt: [RequestCertificateLambdaFunction, Arn]
```

Where `scripts/request-certificate.handler` looks like:

```
import AWS from 'aws-sdk'
import response from 'cfn-response'
import { promisify } from 'util'

import retrieveCertificate from './lib/retrieve-certificate'
import determineImportAndReplace from './lib/determine-import-and-replace'

const ACM = new AWS.ACM({
  apiVersion: '2015-12-08',
  region: 'us-east-1' // ACM certificates must always be stored in us-east-1 with cloudfront
})

const listCertificates = promisify(ACM.listCertificates.bind(ACM))
const importCertificate = promisify(ACM.importCertificate.bind(ACM))

// TODO: to be made dynamic
const opts = {
  leServer: 'production',
  domains: ['tommedema.tk', 'www.tommedema.tk'],
  email: 'tommedema@gmail.com',
  storageBucket: 'XXX-1n7utjoxc94is',
  webBucket: 'XXX-1n7utjoxc94is',
  debug: true
}
 
export const handler = async (event, context) => {
  
  console.log(`request type is ${event.RequestType}`)
  if (['Create', 'Update'].indexOf(event.RequestType) === -1) {
    console.log('can ignore this request type')
    return response.send(event, context, response.SUCCESS, {});
  }
  
  // retrieve an existing certificate from s3 or a new certificate from let's encrypt
  try {
    
    const {
      privkey,
      cert,
      chain,
      subject,
      renewing,
      _expiresAt,
      _issuedAt
    } = await retrieveCertificate(opts)
    
    console.log(`retrieved certificate issued at ${_issuedAt} with subject ${subject}`)
    renewing && console.log(`this is a renewal, new certificate will expire at ${_expiresAt}`)
    
    // compare this certificate with those at ACM
    const { CertificateSummaryList: acmCertificates } = await listCertificates()
    console.log(`retrieved ${acmCertificates.length} existing certificates from ACM`)
    
    let { toImport, acmArn } = await determineImportAndReplace(ACM, acmCertificates, subject, cert)
    console.log(`determined toImport ${toImport} with acmArn ${acmArn}`)
    
    // import a new or replace an existing certificate in ACM
    if (toImport) {
      ({ CertificateArn: acmArn } = await importCertificate({
        Certificate: cert,
        PrivateKey: privkey,
        CertificateChain: chain,
        CertificateArn: acmArn // undefined if a replacement is not necessary
      }))
      
      console.log(`uploaded certificate to ACM with arn ${acmArn}`)
    }
    
    console.log(`responding with certArn ${acmArn}`)
    return response.send(event, context, response.SUCCESS, { certArn: acmArn })
    
  } catch (err) {
    console.error('error while requesting ssl certificate')
    console.error(err)
    return response.send(event, context, response.FAILED, { err })
  }
}
```

This works fine locally. However, when running `sls deploy --verbose`, all I see in Cloudwatch is this:

```
module initialization error: TypeError
```

Of course I could try to monkey-patch my way around this, but I would rather fix the error message. If I could get a line number of file name where things go wrong, and a stack trace, I would know much more than I do now.

My `webpack.config.js` looks like this:

```
const slsw = require('serverless-webpack')
const nodeExternals = require('webpack-node-externals')

module.exports = {
  entry: slsw.lib.entries,
  target: 'node',
  devtool: 'source-map',
  stats: 'errors-only',
  externals: [nodeExternals()],
  module: {
    rules: [
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: __dirname,
        exclude: /node_modules/
      }
    ]
  }
}
```

Do you have an idea on how I can make these cloudwatch errors more descriptive?
