### ISSUE TITLE
Cloudwatch logs do not contain proper stack traces even with sourcemaps enabled

### ISSUE THREAD

**Issue by tommedema** [serverless-heaven/serverless-webpack#297]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
I have a lambda function running on sls deploy through a custom resource, it is packaged with serverless-webpack like any other function.

* What did you expect should have happened?
I expected stack traces to include file name and line number, deobfuscated.

* What was the config you used?

_serverless.yml_
```
frameworkVersion: '=1.24.1'

service: ${{file(./package.json):name}}

plugins:
  # transpile functions' ES7 to ES5 for provider runtime compatibility
  - serverless-webpack
        
custom:
  
  # allows for the exclusion of external modules to webpack
  webpackIncludeModules: true
  packExternalModulesMaxBuffer: 1048576 # 1024 * 1024
    
provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 512
  timeout: 10
  stage: ${{opt:stage, 'dev'}}
  region: ${{opt:region, 'eu-west-2'}}
  variableSyntax: "\\${{([ ~:a-zA-Z0-9._\\'\",\\-\\/\\(\\)]+?)}}" # use ${{}} to access serverless variables
        
package:
  individually: false # FIXME: should be individually after aws-sdk on lambda is version 2.156+
      
functions:
  # special function backing custom resource to generate SSL certificates
  requestCertificate:
    handler: scripts/request-certificate.handler
    timeout: 300
          
resources:
   
  Resources:
    
    # custom resource to retrieve SSL certificates
    CertificateResource:
      Type: Custom::CertificateResource
      Properties:
        RootDomain: tommedema-acm.tk
        ServiceToken:
          Fn::GetAtt: [RequestCertificateLambdaFunction, Arn]
```

_webpack.config.js_
```
const slsw = require('serverless-webpack')
const nodeExternals = require('webpack-node-externals')
const path = require('path')

console.log(`bundling with webpack for environment ${process.env.NODE_ENV}`)

module.exports = {
  entry: slsw.lib.entries,
  target: 'node',
  devtool: 'source-map',
  stats: 'errors-only',
  output: {
    libraryTarget: "commonjs2",
    path: path.join(__dirname, ".webpack"),
    filename: "[name].js",
    sourceMapFilename: "[file].map"
  },
  externals: [nodeExternals()],
  module: {
    rules: [
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: __dirname,
        exclude: /node_modules/
      }
    ]
  }
}
```

_.babelrc_
```
{
  "plugins": ["transform-runtime", "source-map-support"],
  "presets": ["node6", "stage-3"]
}
```

_request-certificate.js_
```
import ACMClient from 'aws-sdk/clients/acm'
import response from 'cfn-response'
import promisify from 'pify'

const ACM = new ACMClient({
  apiVersion: '2015-12-08',
  region: 'us-east-1' // ACM certificates must always be stored in us-east-1 with cloudfront
})

const requestCertificate = promisify(ACM.requestCertificate.bind(ACM))
const describeCertificate = promisify(ACM.describeCertificate.bind(ACM))

export const handler = async (event, context) => {
  
  const rootDomain = event.ResourceProperties.RootDomain
  const mock = event.Mock
    
  console.log(`request type is ${event.RequestType}`)
  if (['Create'].indexOf(event.RequestType) === -1) {
    console.log('can ignore this request type')
    
    return !mock && response.send(event, context, response.SUCCESS, {})
  }
  
  // request a new certificate
  const { CertificateArn: acmArn } = await requestCertificate({
    DomainName: rootDomain,
    SubjectAlternativeNames: [`www.${rootDomain}`],
    ValidationMethod: 'DNS'
  })
  console.log(`requested certificate with arn ${acmArn}`)
  
  // describe the certificate to retrieve DNS validation records
  const { Certificate: certificateDescription } = await describeCertificate({
    CertificateArn: acmArn
  })
  
  // validate that certificate status
  console.log('described certificate: %j', certificateDescription)
  if (!(['PENDING_VALIDATION', 'ISSUED'].includes(certificateDescription.Status))) {
    console.log('certificate is not yet issued and is not pending validation')
    
    return !mock && response.send(event, context, response.FAILED, {
      err: new Error(`requested acm certificate has unexpected 
        status of ${certificateDescription.Status}`)
    })
  }
  
  // destructure the certificate description to retrieve validation dns records
  // these records are only available if the certificate is pending validation
  const {
    DomainValidationOptions: [
      {
        ResourceRecord: {
          Name: rootRecordName,
          Value: rootRecordValue
        }
      },
      {
        ResourceRecord: {
          Name: wwwRecordName,
          Value: wwwRecordValue
        }
      }
    ]
  } = certificateDescription
  console.log(`received validation records with root name ${rootRecordName},
    root value ${rootRecordValue}, www name ${wwwRecordName}, and www value ${wwwRecordValue}`)
  
  return !mock && response.send(event, context, response.SUCCESS, {
    acmArn,
    rootRecordName,
    rootRecordValue,
    wwwRecordName,
    wwwRecordValue
  });
}
```

_package.json_
```
{
  "name": "notes-api",
  "version": "1.0.0",
  "description": "a serverless starter to bootstrap CRUD applications that are 100% version controlled",
  "scripts": {
    "deploy-prod": "export AWS_PROFILE=sls-prod && export AWS_CLIENT_TIMEOUT=300000 && ./node_modules/serverless/bin/serverless deploy --verbose --stage prod --aws-s3-accelerate",
    "deploy-prod-web": "export AWS_PROFILE=sls-prod && export AWS_CLIENT_TIMEOUT=300000 && ./node_modules/serverless/bin/serverless deploy --verbose --stage prod --web --aws-s3-accelerate",
    "remove-prod": "export AWS_PROFILE=sls-prod && export AWS_CLIENT_TIMEOUT=300000 && ./node_modules/serverless/bin/serverless remove --verbose --stage prod",
    "deploy-dev": "export AWS_PROFILE=sls-dev && export AWS_CLIENT_TIMEOUT=300000 && ./node_modules/serverless/bin/serverless deploy --verbose --stage dev --aws-s3-accelerate",
    "deploy-dev-web": "export AWS_PROFILE=sls-dev && export AWS_CLIENT_TIMEOUT=300000 && ./node_modules/serverless/bin/serverless deploy --verbose --stage dev --web --aws-s3-accelerate",
    "remove-dev": "export AWS_PROFILE=sls-dev && export AWS_CLIENT_TIMEOUT=300000 && ./node_modules/serverless/bin/serverless remove --verbose --stage dev",
    "deploy-stage": "export AWS_PROFILE=sls-$STAGE && export AWS_CLIENT_TIMEOUT=300000 && ./node_modules/serverless/bin/serverless deploy --verbose --stage $STAGE --aws-s3-accelerate",
    "deploy-stage-web": "export AWS_PROFILE=sls-$STAGE && export AWS_CLIENT_TIMEOUT=300000 && ./node_modules/serverless/bin/serverless deploy --verbose --stage $STAGE --web --aws-s3-accelerate",
    "remove-stage": "export AWS_PROFILE=sls-$STAGE && export AWS_CLIENT_TIMEOUT=300000 && ./node_modules/serverless/bin/serverless remove --verbose --stage $STAGE",
    "freshtall": "npm cache clean --force && rm -rf node_modules && rm -f package-lock.json && npm install"
  },
  "keywords": [],
  "author": "Tom Medema",
  "license": "MIT",
  "devDependencies": {
    "aws-lambda-mock-context": "^3.1.1",
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-plugin-source-map-support": "^1.0.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-node6": "^11.0.0",
    "babel-preset-stage-3": "^6.24.1",
    "serverless": "^1.24.1",
    "serverless-scriptable-plugin": "^0.6.0",
    "serverless-webpack": "^4.1.0",
    "shelljs": "^0.7.8",
    "standard": "^10.0.3",
    "uuid": "^3.1.0",
    "webpack": "^3.10.0",
    "webpack-node-externals": "^1.6.0"
  },
  "dependencies": {
    "aws-sdk": "^2.166.0",
    "babel-runtime": "^6.26.0",
    "cfn-response": "^1.0.1",
    "dn": "^0.1.5",
    "pify": "^3.0.0",
    "source-map-support": "^0.5.0"
  }
}
```

* What stacktrace or error message from your provider did you see?

In cloudwatch:
```
2017-12-09T14:22:04.926Z	52b2795d-dcec-11e7-aa8a-b91e68e17bbc	(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot match against 'undefined' or 'null'.
```

Similar or dependent issue(s):
* #291

## Additional Data

* ***Serverless-Webpack Version you're using***: 4.1.0
* ***Webpack version you're using***: 3.10.0
* ***Serverless Framework Version you're using***: 1.24.1
* ***Operating System***: OSX Sierra
