### ISSUE TITLE
Receiving no such file or directory /.build/.serverless error while running **sls deploy** . 

### ISSUE THREAD

**Issue by chaitanya145** [serverless-heaven/serverless-webpack#312]
# This is a (Bug Report)

## Description

For bug reports:
* What went wrong?
Receiving no such file or directory /.build/.serverless error while running **sls deploy** . 
ENOENT: no such file or directory, lstat 'C:\_repo\test\.build\.serverless'. 

A Typescript project

* What did you expect should have happened?
The Build is creating .serverless folder under C:\_repo\test\ but looking for the artifact in .build folder. 

* What was the config you used?

> webpack.config.js

```
const path = require('path');
const slsw = require('serverless-webpack');
var nodeExternals = require('webpack-node-externals');
var ProgressBarPlugin = require('progress-bar-webpack-plugin');

console.log(slsw.lib.entries);
console.log(__dirname);

module.exports = {
    entry: slsw.lib.entries,
    target: 'node',
    resolve: {
        extensions: ['.js','.json','.ts']
    },
    output: {
        devtoolModuleFilenameTemplate: '[absolute-resource-path]',
        devtoolFallbackModuleFilenameTemplate: '[absolute-resource-path]?[hash]',
        libraryTarget: 'commonjs',
        path: path.join(__dirname, '.webpack'),
        filename: '[name].js',
    },

    module: {
        loaders: [
            {test: /\.ts(x?)$/, loader: 'ts-loader'},
            {test: /\.js$/,
                loader: "babel-loader",
                include: [
                    path.resolve(__dirname, '.')
                ],
                query: {
                    presets: ['node6']
                }}

        ],
    },
    // do not package node_modules, deploy step adds them
    externals: [nodeExternals({
        whitelist: ['@xxx/models', '@xxx/core-data']
    })],
    stats: {
        colors: true
    },
    devtool: 'source-map',
    plugins: [
        new ProgressBarPlugin()
    ]
};
```
* What stacktrace or error message from your provider did you see?

Similar or dependent issue(s):
* #12345

## Additional Data

* ***Serverless-Webpack Version you're using***:
* ***Webpack version you're using***:
* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace (if available)***:

**Comment by HyperBrain** [comment]
Hi @chaitanya145 . Thanks for reporting. Your error sounds very strange and the webpack config looks ok.

The plugin uses the standard output for it's artifacts (.serverless), so they end up there and does not interfere with Serverless' deployment. I'm not really sure where your `.build` folder comes from. For me it looks like a serverless or serverless configuration issue.

Do you have any additional information that could shed some light on your environment?

**Comment by chaitanya145** [comment]
@HyperBrain Thanks for replying.

here is my **serverless.yml**, 
```
service: test-service

provider:
  name: aws
  runtime: nodejs6.10
  deploymentBucket: test-${opt:stage}
  environment:
    NODE_ENV: ${opt:stage}
  iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DescribeTable
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:BatchGetItem
          - dynamodb:BatchWriteItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
        Resource: "arn:aws:dynamodb:us-east-1:*:*"
      - Effect: Allow
        Action:
          - s3:*
        Resource: "*"

stage: ${opt:stage}
region: us-east-1

functions:
  api:
    handler: src/index.handler
    timeout: 300
    events:
      - http:
          path: "{proxy+}"
          method: any
          cors:
            origins:
              - '*'
            allowCredentials: true

resources:
  - ${file(./.data/resources.yml)}

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-plugin-typescript

  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb:
    start:
      port: 8000
      cors: true
      sharedDb: true
      dbPath: '.'
  serverless-offline:
    location: '.'
  webpackIncludeModules:
    packagePath: './package.json'

```
**Package.json**
```
devDependencies{
    "serverless-dynamodb-local": "^0.2.27",
    "serverless-offline": "^3.16.0",
    "serverless-plugin-typescript": "^1.1.5",
    "serverless-webpack": "^4.2.0",
    "webpack": "^3.6.0",
    "webpack-node-externals": "^1.6.0",
} 
```

Let me know if this info helps
