### ISSUE TITLE
Functions zip gets created but functions folder contains the no-babel parsed file

### ISSUE THREAD

**Issue by martosoler** [serverless-heaven/serverless-webpack#323]
# This is a (Bug Report)

## Description

For bug reports:
* What went wrong?
The function in plain ES6 is uploaded instead of the Babel parsed one in the Zip file created by Webpack.
The problem with this is that (as you can see in the picture), I'm using a module _authentication_ in the function but that module cannot be found in Azure since its not _webpacked_.
* What did you expect should have happened?
The generated file by Webpack to be in the Azure Portal
* What was the config you used?
serverless.yml
```
service: test-functions

provider:
  name: azure
  location: West US

plugins:
  - serverless-azure-functions
  - serverless-webpack

custom:
  webpackIncludeModules: true

functions:
  sendWelcomeEmail:
    handler: src/handler.sendWelcomeEmail
    events:
      - http:
          path: sendWelcomeEmail
          method: post
          x-azure-settings:
            authLevel : anonymous
            methods:
              - post
```

webpack.config.js
```
const slsw = require('serverless-webpack');
const path = require('path');

module.exports = {
  entry: slsw.lib.entries,
  target: 'node',
  module: {
    rules: [{
      test: /\.js$/,
      loader: 'babel-loader',
      exclude: /node_modules/,
    }],
  },
  output: {
    libraryTarget: 'commonjs',
    path: path.resolve(__dirname, '.dist'),
    filename: 'handler.js',
  },
};
```

Project structure
![image](https://user-images.githubusercontent.com/651079/36359516-f31c856c-14fa-11e8-93a9-61647a72b1ef.png)

* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issue(s):

## Additional Data

* ***Serverless-Webpack Version you're using***: 4.3.0
* ***Webpack version you're using***: 3.11.0
* ***Serverless Framework Version you're using***: 1.25.0
* ***Operating System***: Mac OS
* ***Stack Trace (if available)***:
