### ISSUE TITLE
webpackIncludeModules: true not working

### ISSUE THREAD

**Issue by iDVB** [serverless-heaven/serverless-webpack#335]
# This is a (Bug Report / Feature Proposal)
Bug Report

## Description
`cfn-lambda` is 1st Level Dep in `package.json`. 
```
{
  "name": "not telling",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Warn: no test specified\" && exit 0"
  },
  "author": "not telling",
  "license": "ISC",
  "dependencies": {
    "aws-sdk": "^2.197.0",
    "cfn-lambda": "^2.1.1"
  },
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-eslint": "^8.2.2",
    "babel-loader": "^7.1.3",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.26.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-latest": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "babel-types": "^6.26.0",
    "eslint": "^4.18.2",
    "eslint-config-prettier": "^2.9.0",
    "eslint-plugin-import": "^2.9.0",
    "eslint-plugin-prettier": "^2.6.0",
    "prettier": "^1.11.1",
    "prettier-eslint": "^8.8.1",
    "serverless-webpack": "^4.4.0",
    "webpack": "^4.1.0",
    "webpack-node-externals": "^1.6.0"
  },
  "babel": {
    "presets": [
      "stage-0"
    ],
    "plugins": [
      "syntax-trailing-function-commas",
      "transform-async-to-generator",
      "transform-es2015-destructuring",
      "transform-es2015-parameters",
      "transform-es2015-duplicate-keys",
      "transform-es2015-modules-commonjs",
      "transform-exponentiation-operator",
      "transform-runtime"
    ]
  },
  "eslintConfig": {
    "parser": "babel-eslint",
    "extends": [
      "prettier"
    ],
    "plugins": [
      "prettier"
    ],
    "globals": {
      "__DEV__": true
    },
    "env": {
      "node": true
    },
    "rules": {
      "no-underscore-dangle": 2,
      "arrow-parens": "off",
      "generator-star-spacing": "off",
      "no-console": "off",
      "radix": "off",
      "prettier/prettier": [
        "error",
        {
          "singleQuote": true,
          "trailingComma": "all"
        }
      ]
    }
  }
}
```

Added `nodeExternals()` to webpack
```
const slsw = require('serverless-webpack');
const path = require('path');
const nodeExternals = require('webpack-node-externals');

module.exports = {
  entry: slsw.lib.entries,
  target: 'node',
  externals: [nodeExternals()],
  module: {
    rules: [
      {
        test: /\.js?$/,
        // include: [path.resolve(__dirname, 'functions')],
        loader: 'babel-loader',
        options: {
          presets: ['stage-0'],
        },
      },
    ],
  },
  mode: 'production',
};
```

Added `webpackIncludeModules` to `serverless.yaml`
```
service: my-service

custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'logs:CreateLogGroup'
        - 'logs:CreateLogStream'
        - 'logs:PutLogEvents'
      Resource: 'arn:aws:logs:*:*:*'
    - Effect: Allow
      Action:
        - 'elastictranscoder:*'
        - 'iam:PassRole'
      Resource:
        - '*'

functions:
  myfunction:
    handler: functions/handler.somehandler

plugins:
  - serverless-webpack
```

the follow is what I get with `sls package -s dvb -v` and `cfn-lambda` in NOT packaged in the ZIP
```
Serverless: Bundling with Webpack...
Time: 522ms
Built at: 3/6/2018 3:29:22 PM
               Asset      Size  Chunks             Chunk Names
functions/handler.js  1.99 KiB       0  [emitted]  functions/handler
Entrypoint functions/handler = functions/handler.js
   [0] external "aws-sdk" 42 bytes {0} [built]
   [1] external "cfn-lambda" 42 bytes {0} [built]
   [2] external "babel-runtime/helpers/extends" 42 bytes {0} [built]
   [3] external "babel-runtime/helpers/objectWithoutProperties" 42 bytes {0} [built]
   [4] ./functions/Pipeline.js 1.97 KiB {0} [built]
   [5] ./functions/handler.js 805 bytes {0} [built]
Serverless: No external modules needed
Serverless: Packaging service...
```

However, if I set the `serverless.yml` to 
```
custom:
  webpackIncludeModules:
    forceInclude:
      - cfn-lambda
```

Then I get the following output and `cfn-lambda` IS packaged externally
```
Serverless: Bundling with Webpack...
Time: 554ms
Built at: 3/6/2018 3:31:13 PM
               Asset      Size  Chunks             Chunk Names
functions/handler.js  1.99 KiB       0  [emitted]  functions/handler
Entrypoint functions/handler = functions/handler.js
   [0] external "aws-sdk" 42 bytes {0} [built]
   [1] external "cfn-lambda" 42 bytes {0} [built]
   [2] external "babel-runtime/helpers/extends" 42 bytes {0} [built]
   [3] external "babel-runtime/helpers/objectWithoutProperties" 42 bytes {0} [built]
   [4] ./functions/Pipeline.js 1.97 KiB {0} [built]
   [5] ./functions/handler.js 805 bytes {0} [built]
Serverless: Packing external modules: cfn-lambda@^2.1.1
Serverless: Packaging service...
```

For bug reports:
* What went wrong?
External deps not automagically being zipped when using `webpackIncludeModules: true`

* What did you expect should have happened?
When using `webpackIncludeModules: true` and `nodeExternals()` in webpack. I expected all external `node_modules` to be packaged "externally" from webpack build and instead ZIPed into the serverless build.

* What was the config you used?
See above.

* What stacktrace or error message from your provider did you see?
See above.

* ***Serverless-Webpack Version you're using***:
    "serverless-webpack": "^4.4.0",
    "webpack-node-externals": "^1.6.0"
* ***Webpack version you're using***:
    "webpack": "^4.1.0",
* ***Serverless Framework Version you're using***:
v1.26.1
* ***Operating System***:
macOS 10.12.6
* ***Stack Trace (if available)***:
See above.
