### ISSUE TITLE
Need to bundle specific gRPC binary with Lambda function using serverless webpack

### ISSUE THREAD

**Issue by pflugs30** [serverless-heaven/serverless-webpack#342]
* ***Serverless-Webpack Version you're using***:  5.0.0
* ***Webpack version you're using***:  3.11.0
* ***Serverless Framework Version you're using***:  1.26.1
* ***Operating System***: win-64

I'm trying to use the serverless framework to build a Lambda function that pulls messages from Google PubSub.  When using the PubSub NodeJS package, one of the dependencies is gRPC which requires that a binary file be downloaded during the install process.  Since I'm on a windows laptop for dev, the gRPC install script downloads *node-v48-win32-x64-unknown*.  However, Lambda runs on Linux, and it expects build *node-v48-linux-x64-glibc*.  Per [this comment](https://github.com/grpc/grpc/issues/6443#issuecomment-355494910), it is possible to force npm to rebuild the gRPC package to include the Linxu binary.

My problem is that I can't figure out how to include that in the serverless deployment.  When serverless webpack bundles everything up, it includes gRPC with the windows version.  When this whole package is successfully deployed to AWS, the Lambda function throws the following error:

> Unable to import module 'handler': Error
> Expected directory: node-v48-linux-x64-glibc
> Found: [node-v48-win32-x64-unknown]
> This problem can often be fixed by running "npm rebuild" on the current system
> Original error: Cannot find module '/var/task/node_modules/grpc/src/node/extension_binary/node-v48-linux-x64-glibc/grpc_node.node'
>   at Object. (/var/task/node_modules/grpc/src/grpc_extension.js:53:17)...

So my question is: how can I insert the package rebuild command as part of the serverless-webpack process so the correct version of the gRPC binary gets sent to AWS?  It's as if the serverless-webpack is doing a full `npm install`, and I'd like to insert after that is done to rebuild the gRPC module.  I understand that this is a complicated situation and question, and I'm happy to provide any other information.

## Serverless.yaml
```
service: myService

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

plugins:
  # Use serverless-webpack plugin to transpile ES6/ES7
  - serverless-webpack
  - serverless-offline
  
custom:
  webpack:
    includeModules: true # enable auto-packing of external modules

functions:
  pullData:
    handler: handler.pullData
    events:
      - http:
          path: pullData
          method: post
          cors: true
```

## webpack.config.js
```
const path = require('path');
const slsw = require("serverless-webpack");
const nodeExternals = require("webpack-node-externals");

module.exports = {
  entry: './handler.js',
  target: 'node',
  externals: [nodeExternals()],
  module: {
    loaders: [{
      test: /\.js$/,
      loaders: ['babel-loader'],
      include: __dirname,
      exclude: /node_modules/
    }]
  },
  output: {
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '.webpack'),
    filename: 'handler.js'
  }
};
```
