### ISSUE TITLE
Allow script execution and management via packagerOptions

### ISSUE THREAD

**Issue by HyperBrain** [serverless-heaven/serverless-webpack#343]
# This is a Feature Proposal

## Description

Currently the webpack plugin does not allow for custom scripts to be executed while packaging the functions/service. The packager part creates a small package.json that only contains the dependencies to make sure that they are bundled correctly.

Issues like #342 show, that there are cases where invoking a script after the packager install might be needed.

A possible approach would be to add a list of inline scripts as `packageOptions.scripts[]` that are added to the package.json and executed serially with "npm/yarn run" after the install has finshed. The script entries can be anything that is allowed for a package.json script entry. This will give users more power to cover these situations.

Sample for the referenced issue:
```yaml
# serverless.yml
custom:
  webpack:
    packagerOptions:
      scripts:
        - npm rebuild grpc --target=6.1.0 --target_arch=x64 --target_platform=linux
```

Similar or dependent issue(s):
* #342

## Additional Data
N/A
