### ISSUE TITLE
Type Error --- Path must be a string. Received undefined

### ISSUE THREAD

**Issue by mkamrani** [serverless-heaven/serverless-webpack#346]
Trying to check if the serverless-webpack is setup properly for the new project:

> serverless webpack --out dist

I get the error: 

> Serverless:
> WARNING: Entry for events@undefined could not be retrieved.
> Please check your service config if you want to use lib.entries.
> 
>   Type Error ---------------------------------------------
> 
>   Path must be a string. Received undefined

webpack.config.js

```
const path = require('path');
const slsw = require('serverless-webpack');


module.exports = {
    entry: slsw.lib.entries,
    resolve: {
        extensions: [
            '.js',
            '.json',
            '.ts',
            '.tsx'
        ]
    },
    target: 'node',
    output: {
        libraryTarget: 'commonjs',
        path: path.join(__dirname, '.webpack'),
        filename: '[name].js'
    },
    module: {
        rules: {
            test: /\.ts(x?)$/,
            use: [
                {
                    loader: 'ts-loader'
                }
            ]
        }
    }
};
```

serverless.yml

```
service: cashmanager-apis

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-southeast-2
  # environment: '${file(.env.yml):${self:custom.stage}}'

package:
  individually: true
  exclude:
    - src/**/*.spec.ts

functions:
  createUask:
    handler: src/users/createHandler.create
  events:
    - http:
        path: users
        method: put

plugins:
  - serverless-webpack
  - serverless-plugin-typescript
  - serverless-offline
```

tsconfig.json

```
{
    "compilerOptions": {
        "sourceMap": true,
        "lib": [
            "es5",
            "es6",
            "dom",
            "es2015",
            "esnext.asynciterable"
        ]
    }
}
```
devDependencies
```
"devDependencies": {
    "serverless-offline": "^3.18.0",
    "serverless-plugin-typescript": "^1.1.5",
    "serverless-webpack": "^5.0.0",
    "ts-loader": "^4.0.1",
    "webpack": "^4.1.1"
  }
```

file structure:

> .serverless
> .node_modules
> src > users > createHandler.ts
> .gitignore
> package.json
> serverless.yml
> tsconfig.json
> webpack.config.js
> yarn.lock

Thanks for any help
