### ISSUE TITLE
invoke local --watch is not working

### ISSUE THREAD

**Issue by crysislinux** [serverless-heaven/serverless-webpack#349]
# This is a Bug Report

## Description

* What went wrong?
start with
`sls invoke local --function some-function --watch`
when change the code, it recompiles the code,  but it still seems invoke the old compiled result

* What did you expect should have happened?
It should run the latest compiled result just as what the documentation says.

* What was the config you used?

```
service: some-service

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackIncludeModules: true

package:
  individually: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-2

functions:
  some-function:
    handler: some-function/handler.handler
```

* What stacktrace or error message from your provider did you see?
No errors, the output is like this
![image](https://user-images.githubusercontent.com/5404597/37462082-a9ba286c-288b-11e8-92e0-cc1a4b597afb.png)

the second time it should output 5 instead of 6 because the code has changed.

Similar or dependent issue(s):

## Additional Data

* ***Serverless-Webpack Version you're using***:  5.1.0
* ***Webpack version you're using***: 4.1.1
* ***Serverless Framework Version you're using***: 1.26.1
* ***Operating System***: macOs High Sierra  10.13.3
* ***Stack Trace (if available)***:
