### ISSUE TITLE
Running serverless offline with --skipCacheInvalidation does not update code

### ISSUE THREAD

**Issue by gideonairex** [serverless-heaven/serverless-webpack#352]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
Executed ```serverless offline --skipCacheInvalidation start```.
 Then used ```--skipCacheInvalidation``` to make a cache connection to mongodb. What happens is that when trying to change the code it did not update.
* What did you expect should have happened?
Expecting that it would update the code base on the documentation it automatically updates
 then recompile if there are new changes.
* What was the config you used?
```
service: service-name

frameworkVersion: "1.26.*"

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, "dev"}
  logRetentionInDays: 7
  memorySize: 128
  timeout: 10
  environment: ${file(./env.yml):${opt:stage, "staging"}}

### PLUGINS
plugins:
  - serverless-webpack
  - serverless-domain-manager
  - serverless-offline

custom:
  webpackIncludeModules: true
  domains:
    prod: api.domain.com
    staging: staging-api.domain.com
    dev: dev-api.domain.com
  customDomain:
    basePath: ${self:service}
    domainName: ${self:custom.domains.${self:provider.stage}}
    stage: ${self:provider.stage}
    createRoute53Record: true

### FUNCTIONS
functions: ${file(./functions.yml):functions}
```

Then this is my webpack config
```
const path = require('path');
const nodeExternals = require('webpack-node-externals');
const slsw = require('serverless-webpack');

module.exports = {
  entry: slsw.lib.entries,
  target: 'node',
  externals: [nodeExternals()],
  output: {
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js'
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        use: [
          {
            loader: 'babel-loader'
          }
        ],
      }
    ]
  }
};
```
* What stacktrace or error message from your provider did you see?
There was no error but the code did not update.
<img width="1010" alt="screen shot 2018-03-20 at 8 40 36 pm" src="https://user-images.githubusercontent.com/6386061/37655035-15ae6488-2c7f-11e8-98c1-23ee5dfa5b06.png">

## Additional Data

* ***Serverless-Webpack Version you're using***: serverless-webpack@5.1.0
* ***Webpack version you're using***: webpack@3.11.0
* ***Serverless Framework Version you're using***: 1.26.0
* ***Operating System***: macOS High Sierra 10.13.3
* ***Stack Trace (if available)***: see image above.
