### ISSUE TITLE
Bug: module initialization error: TypeError

### ISSUE THREAD

**Issue by warrenronsiek** [serverless-heaven/serverless-webpack#353]
# This is a Bug Report

## Description
* What went wrong? 

Just switched to deployment using serverless-webpack (I used to manually build then deploy). Functions that used to work now get a TypeError. I've checked the deployment package and the functions are in there. Furthermore, when the function is executed it will load the requirements and imports (e.g. in the code below, it will successfully log "finished imports"), but the second it gets to executing the main function I get the TypeError - it won't even run the first `console.log(event)` line. 
* What did you expect should have happened? 

Function runs without TypeError.
* What was the config you used?

project structure:
```
lib/getNodeInfo.js
lib/[other functions].js
lib/common/tableNames.js
lib/common/[other utility functions].js
webpack.config.js
serverless.yml
package.json
[other .ignore or .lock files]
```

webpack.config.js:
```
const path = require('path');
const webpack = require('webpack');
const slsw = require('serverless-webpack');

const build = {
  entry: slsw.lib.entries,
  resolve: {
    extensions: ['.js']
  },
  target: 'node',
  output: {
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js'
  },
  mode: 'development',
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: [{
          loader: 'babel-loader'
        }]
      }
    ]
  },
  externals: ["aws-sdk"]
};

module.exports = build;
```

serverless.yml
```
provider:
  name: aws
  region: us-west-2
  stage: ${opt:stage, self:custom.default_stage}
  runtime: nodejs6.10
  memorySize: 128
  apiKeys:
    - [api key]
  environment:
    stage: ${self:provider.stage}
    [ other env vars]
  iamRoleStatements:
    [iam roles]

custom:
  default_stage: dev

plugins:
  - serverless-webpack

package:
  exclude:
    - package.json
    - test/**
    - .git
    - .gitignore
    - .npmignore
    - .idea/**
    - node_modules/**
    - '!node_modules/jwt-decode/**'
    - '!node_modules/uuid/**'

functions:
... 
  getNodeInfo:
    handler: lib/getNodeInfo.getNodeInfo
    events:
      - http:
          method: POST
          path: get-node-info
          private: true
...
```
package.json
```
{
"dependencies": {
    "@types/lodash": "^4.14.91",
    "@types/node": "^8.5.1",
    "aws-sdk": "^2.93.0",
    "lodash": "^4.17.4",
    "stripe": "^4.23.1",
    "uuid": "^3.1.0"
  },
  "devDependencies": {
    "babel-core": "^6.25.0",
    "babel-loader": "^7.1.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "fs": "0.0.1-security",
    "ignore-loader": "^0.1.2",
    "jest": "^19.0.2",
    "jst-loader": "^1.0.1",
    "jwt-decode": "^2.2.0",
    "serverless-webpack": "^5.1.0",
    "typescript": "^2.4.2",
    "webpack": "^4.1.1",
    "webpack-cli": "^2.0.12"
  }
}
```
getNodeInfo.js
```
import tableNames from './common/tableNames'
const aws = require('aws-sdk');
const ddb = new aws.DynamoDB({apiVersion: '2012-08-10'});
console.log('finished imports');

module.exports.getNodeInfo = function (event, context, callback) {
  console.log(event);
  const nodeId = JSON.parse(event.body).nodeId;

  const response = (nodeInfo) => {
    if (Object.keys(nodeInfo).length === 0 && nodeInfo.constructor === Object) {
      return {
        statusCode: 200,
        headers: {},
        body: JSON.stringify({message: 'NodeDoesNotExist', nodeInfo: nodeInfo})
      }
    } else {
      return {
        statusCode: 200,
        headers: {},
        body: JSON.stringify({message: 'GetNodeInfoSuccessful', nodeInfo: nodeInfo})
      }
    }
  };

  const getNodeParams = () => {
    return {
      TableName: tableNames.nodeTable,
      Key: {
        NodeId: {
          S: nodeId
        }
      }
    }
  };

  const getNodeRequest = ddb.getItem(getNodeParams()).promise();
  getNodeRequest
    .then(res => {
      console.log(res);
      callback(null, response(res))
    })
    .catch(err => {
      console.log(err);
      callback(err)
    })
};
```
* What stacktrace or error message from your provider did you see?
```
module initialization error: TypeError
at Object.eval (webpack:///./lib/getNodeInfo.js?:12:28)
at eval (webpack:///./lib/getNodeInfo.js?:52:30)
at Object../lib/getNodeInfo.js (/var/task/lib/getNodeInfo.js:100:1)
at __webpack_require__ (/var/task/lib/getNodeInfo.js:23:30)
at /var/task/lib/getNodeInfo.js:75:18
at Object.<anonymous> (/var/task/lib/getNodeInfo.js:78:10)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
```

Similar or dependent issue(s):
* #291 
* #230 

## Additional Data

* ***Serverless-Webpack Version you're using***: "^5.1.0"
* ***Webpack version you're using***: "^4.1.1"
* ***Serverless Framework Version you're using***: 1.26.1
* ***Operating System***: MacOS

**Comment by HyperBrain** [comment]
Hi @warrenronsiek ,

There are some configuration issues, You should change the files as follow and it should work:

```js
// webpack.config.js
const nodeExternals = require('webpack-node-externals');   // Add the module to your dev dependencies!
  ...
  mode: slsw.lib.webpack.isLocal ? 'development' : 'production',
  optimization: {
    // Do not minimize the code.
   minimize: false
  },
  performance: {
    // Turn off size warnings for entry points
    hints: false
  },
  externals: [ nodeExternals() ],
  ...
```

```yaml
# serverless.yml
...
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
...

# Remove package:exclude completely. sls-webpack does its own optimized packaging
# and only includes the needed files
```

```
// package.json

Move aws-sdk to `devDependencies`
Add 'webpack-node-externals' to devDependencies as noted above.
Use 'babel-loader' at least with version '^7.1.3' - earlier version do not support webpack 4
You do not need the 'webpack-cli' for the plugin - only if you want to do some independent local tests
Add 'babel-plugin-source-map-support' to the devDependencies
Add 'source-map-support' to the dependencies
```

Finally, add a '.babelrc' file to configure babel properly (especially the env preset):
```js
{
  "comments": false,
  "presets": [ 
    [ "env", { "node": "6.10" }
  ],
  "plugins": [
    "transform-decorators-legacy",     // If you want to use the decorators plugin in your code
    "source-map-support"
  ]
}
```

After you did these changes, your project will deploy and run properly. Please let me know if that fixes your problems.
