### ISSUE TITLE
Cannot find module Invoke Local

### ISSUE THREAD

**Issue by pizza-r0b** [serverless-heaven/serverless-webpack#356]
Using webpack 4 - having checked against the webpack 4 example - when I run `sls invoke local -f functionName` webpack bundles my functions to the specified `.webpack/` directory. After building the error `Error: Cannot find module '..../.webpack/upload'` is thrown. The build output structure is .webpack/upload/functions/upload. 

Heres the serverless config and I used the example webpack config and got the error

```yml
service: api 

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    NODE_ENV: ${file(${opt:config}):NODE_ENV, self:custom.NODE_ENV}

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  webpack:
    webpackConfig: ./webpack/prod.js
    includeModules: true
    packager: 'yarn'
  NODE_ENV: 'development'
functions:
  upload:
    handler: ./functions/upload.upload
    events:
      - http:
          path: models/v1/upload
          method: get
          cors: true
```
