### ISSUE TITLE
How to include files in output zip file?

### ISSUE THREAD

**Issue by panzupa** [serverless-heaven/serverless-webpack#361]
Hi,

One of the dependencies that I use includes binary files. I want those binary files to be packed in the output zip file so the lambda functions can use them during runtime.

How can I achieve that?

I already tried to use 'file-loader' in webpack.config.js which didn't work and I tried in my serverless.yml
```
custom:
  webpack:
    includeModules:
      forceInclude:
        - module_name_with_binary_files
```

All I get are just transpiled js files of my functions.
