### ISSUE TITLE
Offline Builds Working, Errors On Deployment

### ISSUE THREAD

**Issue by Saeris** [serverless-heaven/serverless-webpack#389]
# This is a Bug Report

## Description

Local offline builds compile and run just fine, but when running `serverless deploy` builds fail with the following error:

```bash
$ yarn deploy:dev
yarn run v1.5.1
$ serverless --stage=dev deploy
Serverless: Bundling with Webpack...
Hash: 553b3b231bc8271d903c
Version: webpack 4.8.2
Time: 86ms
Built at: 2018-05-11 15:54:21
           Asset       Size  Chunks  Chunk Names
    api/index.js   3.97 KiB       0  api/index
api/index.js.map  465 bytes       0  api/index
Entrypoint api/index = api/index.js api/index.js.map
[0] ./api/index.js 1.26 KiB {0} [built] [failed] [1 error]

ERROR in ./api/index.js
Module build failed: Error: [BABEL] D:\GitHub\mini-movie-db\api\index.js: .definitions is not a valid Plugin property
    at D:\GitHub\mini-movie-db\node_modules\@babel\core\lib\config\validation\plugins.js:54:56
    at Array.forEach (<anonymous>)
    at validatePluginObject (D:\GitHub\mini-movie-db\node_modules\@babel\core\lib\config\validation\plugins.js:52:20)
    at D:\GitHub\mini-movie-db\node_modules\@babel\core\lib\config\full.js:215:53
    at cachedFunction (D:\GitHub\mini-movie-db\node_modules\@babel\core\lib\config\caching.js:42:17)
    at loadPluginDescriptor (D:\GitHub\mini-movie-db\node_modules\@babel\core\lib\config\full.js:207:10)
    at D:\GitHub\mini-movie-db\node_modules\@babel\core\lib\config\full.js:64:16
    at Array.map (<anonymous>)
    at recurseDescriptors (D:\GitHub\mini-movie-db\node_modules\@babel\core\lib\config\full.js:63:36)
    at loadFullConfig (D:\GitHub\mini-movie-db\node_modules\@babel\core\lib\config\full.js:112:6)
    at D:\GitHub\mini-movie-db\node_modules\@babel\core\lib\transform.js:28:33
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

  Error --------------------------------------------------

  Webpack compilation error, see above

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     win32
     Node Version:           8.9.4
     Serverless Version:     1.27.2

error An unexpected error occurred: "Command failed.
Exit code: 1
Command: C:\\WINDOWS\\system32\\cmd.exe
Arguments: /d /s /c serverless --stage=dev deploy
Directory: D:\\GitHub\\mini-movie-db
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "D:\\GitHub\\mini-movie-db\\yarn-error.log"
.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Previously deployments have worked no problem, there have been no changes to `serverless.yml` or `webpack.api.config.js`. (Webpack config file name is set in `serverless.yml`) Here are the configs:

```yml
service: mini-movie-db

frameworkVersion: ">=1.21.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-west-2
  environment:
    apikey: ${file(./serverless.env.yml):movieDBApiKey, ""}
    stage: ${opt:stage, ""}

plugins:
  - serverless-prune-plugin
  - serverless-webpack
  - serverless-offline

package:
  individually: true

custom:
  serverless-offline:
    port: 1337
  prune:
    automatic: true
    number: 3
  webpack:
    includeModules: true
    packager: 'yarn'
    webpackConfig: 'webpack.api.config.js'

functions:
  api:
    handler: api/index.graphqlHandler
    events:
      - http:
          path: "{proxy+}"
          method: any
          cors: true
  playground:
      handler: api/playground.playgroundHandler
      events:
        - http:
            path: "/playground"
            method: get
            cors: true
```

```javascript
const { join } = require(`path`)
const slsw = require(`serverless-webpack`) // https://github.com/serverless-heaven/serverless-webpack
const nodeExternals = require(`webpack-node-externals`) // https://github.com/liady/webpack-node-externals

module.exports = {
  mode: slsw.lib.webpack.isLocal ? `development` : `production`,
  entry: slsw.lib.entries,
  target: `node`,
  externals: [nodeExternals()],
  devtool: `nosources-source-map`,
  output: {
    libraryTarget: `commonjs`,
    path: join(__dirname, `.webpack`),
    filename: `[name].js`,
    sourceMapFilename: `[file].map`
  },
  stats: {
    colors: true,
    reasons: false,
    chunks: false
  },
  performance: {
    hints: false
  },
  optimization: {
    minimize: false
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        loader: `babel-loader`,
        exclude: /node_modules/,
        options: {
          babelrc: false,
          plugins: [require(`@babel/plugin-transform-runtime`)],
          presets: [
            [require(`@babel/preset-env`), { targets: { node: `8.10` } }],
            [require(`@babel/preset-stage-0`), { decoratorsLegacy: true }]
          ]
        }
      },
      { test: /\.(graphql|gql)$/, exclude: /node_modules/, loader: `graphql-tag/loader` }
    ]
  }
}
```

Here's the repo for the project if you would like to try and reproduce the error yourself:
https://github.com/Saeris/mini-movie-db/tree/develop

I know the error output says `babel` is throwing the error, but that doesn't appear to be the source of the issue since `webpack` and `babel` appear to work just fine when running offline.

## Additional Data
- OS: win32
- Node Version: 8.9.4
- Yarn Version: 1.5.1
- Serverless Version: 1.27.2
- Serverless-Webpack Version: 5.1.5
