### ISSUE TITLE
Packager: 'yarn' Install error. Should be add not install in /lib/packagers/yarn.js

### ISSUE THREAD

**Issue by michaelwclark** [serverless-heaven/serverless-webpack#400]
# This is a Bug Report 

## Description

* What went wrong?
Yarn installation of packages during `serverless package` errors. NPM does not

* What did you expect should have happened?
Successfull package installs
* What was the config you used?
## serverless.yml
```
service: example

provider:
  name: openwhisk

functions:
  asyncHello:
    handler: functions/handler.asyncHello
  
plugins:
  - serverless-openwhisk
  - serverless-webpack

custom:
  webpack:
    webpackConfig: 'webpack.config.js'   # Name of webpack configuration file
    includeModules: true    # Node modules configuration for packaging
    packager: 'yarn'   # Packager that will be used to package your external modules
    
package:
  individually: true
```

## webpack.config.js
```
const path = require('path');
const slsw = require('serverless-webpack');
const nodeExternals = require('webpack-node-externals');

module.exports = {
  entry: slsw.lib.entries,
  target: 'node',
  mode: slsw.lib.webpack.isLocal ? 'development': 'production',
  optimization: {
    // We no not want to minimize our code.
    minimize: false
  },
  performance: {
    // Turn off size warnings for entry points
    hints: false
  },
  devtool: 'nosources-source-map',
  externals: [nodeExternals()],
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: [
          {
            loader: 'babel-loader'
          }
        ],
      }
    ]
  },
  output: {
    libraryTarget: 'commonjs2',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js',
    sourceMapFilename: '[file].map'
  }
};
```
* What stacktrace or error message from your provider did you see?
```
  yarn install --frozen-lockfile --non-interactive failed with code 1

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
```

## Additional Data
[change this line](https://github.com/serverless-heaven/serverless-webpack/blob/e1bbace9abf16e6cd2ad353db7ff7d1bef0a33af/lib/packagers/yarn.js#L108) 
should be `add` not `install` 

LMK if you need me to PR this.

* ***Serverless-Webpack Version you're using***:    ^5.1.5
* ***Webpack version you're using***:^4.8.3"
* ***Serverless Framework Version you're using***: 1.27.3
* ***Operating System***: OSX
