### ISSUE TITLE
Error using sequence in Serverless.yml due to entries validation failing

### ISSUE THREAD

**Issue by michaelwclark** [serverless-heaven/serverless-webpack#410]
# This is a (Bug Report )

## Description
When using sequence exclusivly in serverless.yml  there is an error [here](https://github.com/serverless-heaven/serverless-webpack/blob/d542eb63bad77ccf42edea7f7a3abcdbb14f6720/lib/validate.js#L178)
 
For bug reports:
* What went wrong?
Error when validating sls.lib.entries internally to this project.
* What did you expect should have happened?
The entries validator should take into account functions that use sequence rather than handler. They are mutually exclusive in the serverless.yml. 
* What was the config you used?
serverless.yml excerpt
```
functions:
  dbInit:
    handler: functions/denim-db.init
    runtime: nodejs:8
    overwrite: true
    parameters:
      DB_URL: "${env:DB_URL}"
      DB_SSL_ENABLED: ${env:DB_SSL_ENABLED}

  graph:
    handler: functions/denim-graph.graphql
    runtime: nodejs:8
    overwrite: true

  graphql:
    sequence: # Use sequences rather than handler to handle events. handler and sequence properties are mutually exclusive.
      - dbInit
      - graph
    overwrite: true
    annotations:
      web-export: true
    events:
      - http: POST /api/graphql
      - http: GET /api/graphql
```
webpack.config.js
```
const path = require('path')
const slsw = require('serverless-webpack')
const nodeExternals = require('webpack-node-externals')

module.exports = {
  entry: slsw.lib.entries,
  target: 'node',
  mode: slsw.lib.webpack.isLocal ? 'development' : 'production',
  optimization: {
    // We no not want to minimize our code.
    minimize: false
  },
  performance: {
    // Turn off size warnings for entry points
    hints: false
  },
  devtool: 'nosources-source-map',
  externals: [nodeExternals()],
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: [
          {
            loader: 'babel-loader'
          }
        ]
      },
      {
        test: /\.(pem)$/,
        use: [
          {
            loader: 'raw-loader',
            options: {
              // emitFile: true,
              useRelativePath: true
            }
          }
        ]
      }
    ]
  },
  output: {
    libraryTarget: 'commonjs2',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js',
    sourceMapFilename: '[file].map'
  }
}
```

* What stacktrace or error message from your provider did you see?
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:28:11)
    at Object.relative (path.js:1265:5)
    at _.map.funcName (/Users/denim_michaelclark/Projects/denim-graph/node_modules/serverless-webpack/lib/validate.js:178:36)
    at arrayMap (/Users/denim_michaelclark/Projects/denim-graph/node_modules/lodash/lodash.js:639:23)
    at Function.map (/Users/denim_michaelclark/Projects/denim-graph/node_modules/lodash/lodash.js:9554:14)
    at ServerlessWebpack.validate (/Users/denim_michaelclark/Projects/denim-graph/node_modules/serverless-webpack/lib/validate.js:173:35)
From previous event:
    at Object.webpack:validate:validate [as hook] (/Users/denim_michaelclark/Projects/denim-graph/node_modules/serverless-webpack/index.js:157:10)
    at BbPromise.reduce (/Users/denim_michaelclark/Projects/denim-graph/node_modules/serverless/lib/classes/PluginManager.js:372:55)
From previous event:
    at PluginManager.invoke (/Users/denim_michaelclark/Projects/denim-graph/node_modules/serverless/lib/classes/PluginManager.js:372:22)
    at PluginManager.spawn (/Users/denim_michaelclark/Projects/denim-graph/node_modules/serverless/lib/classes/PluginManager.js:390:17)
    at ServerlessWebpack.BbPromise.bind.then (/Users/denim_michaelclark/Projects/denim-graph/node_modules/serverless-webpack/index.js:100:51)
From previous event:
    at Object.before:package:createDeploymentArtifacts [as hook] (/Users/denim_michaelclark/Projects/denim-graph/node_modules/serverless-webpack/index.js:100:10)
    at BbPromise.reduce (/Users/denim_michaelclark/Projects/denim-graph/node_modules/serverless/lib/classes/PluginManager.js:372:55)
From previous event:
    at PluginManager.invoke (/Users/denim_michaelclark/Projects/denim-graph/node_modules/serverless/lib/classes/PluginManager.js:372:22)
    at PluginManager.run (/Users/denim_michaelclark/Projects/denim-graph/node_modules/serverless/lib/classes/PluginManager.js:403:17)
    at variables.populateService.then (/Users/denim_michaelclark/Projects/denim-graph/node_modules/serverless/lib/Serverless.js:102:33)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Serverless.run (/Users/denim_michaelclark/Projects/denim-graph/node_modules/serverless/lib/Serverless.js:89:74)
    at serverless.init.then (/Users/denim_michaelclark/Projects/denim-graph/node_modules/serverless/bin/serverless:42:50)
    at <anonymous>
```

## Additional Data
* ***Serverless-Webpack Version you're using***: "^5.1.5"
* ***Webpack version you're using***:  "^4.8.3"
* ***Serverless Framework Version you're using***: "^1.27.3"
* ***Operating System***: OSX
* ***Stack Trace (if available)***: see above

**Comment by HyperBrain** [comment]
Hi @michaelwclark , the reason of the failing validation is, that your function declaration for `graphql` is not a valid Serverless Framework function definition:
```
graphql:
    sequence: # Use sequences rather than handler to handle events. handler and sequence properties are mutually exclusive.
      - dbInit
      - graph
    overwrite: true
    annotations:
      web-export: true
    events:
      - http: POST /api/graphql
      - http: GET /api/graphql
```
Valid function declarations must contain a handler definition.
The `serverless-webpack` plugin strictly relies on the requirements defined by Serverless. Do you use any 3rd party plugin, that uses this function structure?

As the plugin does not (and should not) have any knowledge of semantics introduced by 3rd party plugins, it should be the other plugin's responsibility to map its understanding of "sequence" into valid function definitions (during execution).
