### ISSUE TITLE
How to use in Monorepo without producing tons of duplicate code.

### ISSUE THREAD

**Issue by khrome83** [serverless-heaven/serverless-webpack#430]
# This is a (Bug Report / Feature Proposal)

Question / Clarification

## Description

How do you use this within a Monorepo. Ideally you would define a single webpack.config.js and .babelrc file, and no matter the services, it should share that config. It seems when I specify a webpack.config.js in root, it assumes the functions are located there.

What is the best practices? Is this supported?

**Comment by rbobko93** [comment]
In order to have multiple functions in different folders you have to add this to your webpack confg:

`module.exports = {
    entry: slsw.lib.entries
};`

It takes all functions from your serverless config which contains paths to all functions handlers. For example your serverless.yml file can look like this:

`
functions:
  trackFulfillment:
    handler: src/functions/track/fulfillment/handler.trackFulfillment
  trackValidation:
    handler: src/functions/track/validation/handler.trackValidation
  feedbackFulfillment:
    handler: src/functions/feedback/fulfillment/handler.feedbackFulfillment
  feedbackValidation:
    handler: src/functions/feedback/validation/handler.feedbackValidation
`

When configured like this you don't need to change anything in webpack config whenever new function is added.

**Comment by khrome83** [comment]
@rbobko93 - I did discover this, but this makes sense if I have one servless.yml file. 

I am looking at a structure more like below. Each services has a `package.json` and a `serverless.yml`.

I am curious if each serverless.yml should be configured like something below - What is the best practice. Does each `package.json` need to have webpack and babel plugin inside of each service, or is there a way to contain this at root to reduce code?

In a traditional node monorepo, I would have a separate package.json in each separated concerns. How do you mimic that structure with the least code copy/pasted between them. Does this make more sense?

## My Current Folder Structure
``` http
package.json
webpack.config.js
.babelrc
jest.config.js
resources/
  dynamo-table.yml
  s3-bucket.yml
  package.json
  serverless.yml
services/
  users/
    create.js
    create.test.js
    list.js
    list.test.js
    delete.js
    delete.test.js
    update.js
    update.test.js
    get.js
    get.test.js
    package.json
    serverless.yml
  projects/
    create.js
    create.test.js
    list.js
    list.test.js
    delete.js
    delete.test.js
    update.js
    update.test.js
    get.js
    get.test.js
    package.json
    serverless.yml
  etc/
    ...
```

### Example Service Yaml File
```
service: service-name

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-domain-manager
  - serverless-plugin-stage-variables

custom:
  webpack:
    webpackConfig: ../../webpack.config.js
    includeModules:
      forceExclude:
        - aws-sdk
  stage: ${opt:stage, self:provider.stage}
  stageVariables:
    env: ${self:custom.stage}
  tables:
    projects: projects-${self:custom.stage}
  domains:
    prod: api.example.com
    stage: stage-api.example.com
    dev: dev-api.example.com
  customDomain:
    domainName: ${self:custom.domains.${self:custom.stage}}
    basePath: 'projects'
    stage: ${self:custom.stage}
    createRoute53Record: true
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: migrations

package:
  exclude:
  - coverage/**
  - migrations/**
  - .circleci/**
  - .git/**
  - tests/**

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:*:*:table/${self:custom.tables.projects}"

functions:
  create:
    handler: create.default
    events:
      - http:
          path: /
          method: post
          cors: true
    environment:
      PROJECTS_TABLE: ${self:custom.tables.projects}

  list:
    handler: list.default
    events:
      - http:
          path: /
          method: get
          cors: true
    environment:
      PROJECTS_TABLE: ${self:custom.tables.projects}

  get:
    handler: get.default
    events:
      - http:
          path: /{id}
          method: get
          cors: true
    environment:
      PROJECTS_TABLE: ${self:custom.tables.projects}

  update:
    handler: update.default
    events:
      - http:
          path: /{id}
          method: put
          cors: true
    environment:
      PROJECTS_TABLE: ${self:custom.tables.projects}

  delete:
    handler: delete.default
    events:
      - http:
          path: /{id}
          method: delete
          cors: true
    environment:
      PROJECTS_TABLE: ${self:custom.tables.projects}
```
