### ISSUE TITLE
Lambda inside subdirectory does not load

### ISSUE THREAD

**Issue by prijuly2000** [serverless-heaven/serverless-webpack#432]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
I have subdirectories for each lambda. Locally they work but when deployed, they dont.
* What did you expect should have happened?
* What was the config you used?
Following is my config:
```
provider:
  name: aws
  runtime: nodejs8.10
  profile: default
  region: us-east-1
  memorySize: 512
  apiKeys:
    - mySecretAPIKey
  package:
    individually: true
  plugins:
    - serverless-webpack
    - serverless-dynamodb-local
    - serverless-offline
  custom:
    webpack:
      webpackConfig: 'webpack.config.js'
      includeModules: true
      packager: 'npm'
    serverless-offline:
      babelOptions:
        presets: ["es2015", "stage-2"]
    dynamodb:
      start:
        port: 8000
        inMemory: false
        migrate: true
        seed: true
  resources:
    Resources:
      WearatecDB:
        Type: 'AWS::DynamoDB::Table'
        Properties:
          AttributeDefinitions:
            -
              AttributeName: emailid
              AttributeType: S
          KeySchema:
            -
              AttributeName: emailid
              KeyType: HASH
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
          TableName: Users
functions:
  register:
    handler: register/index.handler
    events:
      - http:
          path: register
          method: post
plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-webpack

```
Folder structure
```
root
   |  =>  serverless.yml
   | =>  register
                => index.js => handler function to handler lambda functionality.
   | => webpack.config.js
```

webpack.config.js
```
/* eslint-disable */
const slsw = require("serverless-webpack");
const nodeExternals = require("webpack-node-externals");

module.exports = {
  entry: slsw.lib.entries,
  target: "node",
  devtool: 'source-map',
  mode: slsw.lib.webpack.isLocal ? "development" : "production",
  externals: [ nodeExternals() ],
  optimization: {
    minimize: false
  },
  performance: {
    hints: false
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        loader: "babel-loader",
        include: [__dirname,"node_modules"]
      }
    ]
  }
};
```
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issue(s):

## Additional Data

* ***Serverless-Webpack Version you're using***:  5.2.0
* ***Webpack version you're using***: 4.16.4
* ***Serverless Framework Version you're using***: latest
* ***Operating System***: mac
* ***Stack Trace (if available)***:
aws cloudwatch log
```
Unable to import module 'register/index': Error
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/var/task/register/index.js:97:18)
at __webpack_require__ (/var/task/register/index.js:20:30)
at Object.<anonymous> (/var/task/register/index.js:187:18)
at __webpack_require__ (/var/task/register/index.js:20:30)
at /var/task/register/index.js:84:18
at Object.<anonymous> (/var/task/register/index.js:87:10)
```
