### ISSUE TITLE
Exclude nested dependencies

### ISSUE THREAD

**Issue by victorbartel** [serverless-heaven/serverless-webpack#447]
# This is an issue related to exclusion of nested dependencies

## Description

When you need to exclude a first level dependency, for example `aws-sdk`, you can achieved it with:
```yml
custom:
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk
```

But what about libraries that depend on `aws-sdk` and include it to their nested `node_modules` folder?
I've tried to fix it with:
```yml
custom:
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk
        - amazon-dax-client/node_modules/aws-sdk
```
But with no luck.
