### ISSUE TITLE
Assertion failed: (!(handle->flags & UV_CLOSED)), function uv__finish_close, file ../deps/uv/src/unix/core.c, line 251.

### ISSUE THREAD

**Issue by AkivaLandsberg** [serverless-heaven/serverless-webpack#492]
# This is a Bug Report
## Description
This is the error I am getting.
```
Serverless: Invoke webpack:compile:watch
Assertion failed: (!(handle->flags & UV_CLOSED)), function uv__finish_close, file ../deps/uv/src/unix/core.c, line 251.
error Command failed with signal "SIGABRT".
```

For bug reports:
* What went wrong?
Crashes during development.
* What did you expect should have happened?
That there should not be an error.
* What was the config you used?
Running serverless framework with the following plugins:
plugins:
  
```yaml
plugins:
  - serverless-offline
  - serverless-plugin-warmup
  - serverless-webpack
  - serverless-plugin-tracing

custom:
  webpack:
    webpackConfig: "webpack.config.js" # Name of webpack configuration file
    includeModules:
      forceInclude:
        - mysql2
      forceExclude:
        - aws-sdk
```

This is my webpack config:
```javascript
module.exports = {
  entry: slsw.lib.entries,
  target: "node",
  mode: slsw.lib.webpack.isLocal ? "development" : "production",
  externals: [nodeExternals()],
  module: {
    rules: [
      {
        test: /\.js$/,
        loader: "babel-loader",
        include: __dirname,
        exclude: /node_modules/
      }
    ]
  }
};
```
* What stacktrace or error message from your provider did you see?
```
Assertion failed: (!(handle->flags & UV_CLOSED)), function uv__finish_close, file ../deps/uv/src/unix/core.c, line 251.
error Command failed with signal "SIGABRT".
```

.babelrc
```json
{
  "plugins": ["transform-runtime"],
  "presets": ["env", "stage-3"]
}
```
relevent dependecies

```json
"dependencies": {
    "babel-runtime": "^6.26.0"
  },
  "devDependencies": {
    "aws-sdk": "^2.192.0",
    "babel-core": "^6.26.0",
    "babel-loader": "^8.0.5",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-stage-3": "^6.24.1",
    "serverless-offline": "^4.9.4",
    "serverless-plugin-tracing": "^2.0.0",
    "serverless-plugin-warmup": "^4.5.3-rc.1",
    "serverless-webpack": "^5.2.0",
    "webpack": "^4.30.0",
    "webpack-node-externals": "^1.7.2"
  }
```

* ***Serverless-Webpack Version you're using***: 5.2.0
* ***Webpack version you're using***: 4.30.0
* ***Serverless Framework Version you're using***: 1.40.0
* ***Operating System***:  macOS 10.14.3 
* ***Stack Trace (if available)***:
