### ISSUE TITLE
Individually packaged functions don't include non node_modules dependencies

### ISSUE THREAD

**Issue by mushketyk** [serverless-heaven/serverless-webpack#498]
# This is a Bug Report 

## Description

For bug reports:
* What went wrong?
I have two files in my project: a handler and a file with DynamoDB utilities:

```
/src
  /dynamoDb
    dynamoDbAccess.ts
  handler.ts
```

If I package functions individually webpack includes the compiled `handler.js` but does not include the `dynamoDb` directory.

Everything works fine if I don't package functions individually.  

* What did you expect should have happened?

The content of the `dynamoDb` folder is compiled and included in the zip archive

* What was the config you used?

serverless.yml

```yml
plugins:
  - serverless-webpack
  - serverless-reqvalidator-plugin
  - serverless-aws-documentation
  - serverless-plugin-canary-deployments
  - serverless-dynamodb-local
  - serverless-offline

package:
  individually: true

custom:
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk
        - source-map-support

```

webpack.config.js:

```js
const path = require('path');
const slsw = require('serverless-webpack');
const nodeExternals = require('webpack-node-externals');

module.exports = {
  mode: slsw.lib.webpack.isLocal ? 'development' : 'production',
  entry: slsw.lib.entries,
  externals: [nodeExternals()],
  devtool: 'source-map',
  resolve: {
    extensions: ['.js', '.jsx', '.json', '.ts', '.tsx'],
  },
  output: {
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js',
  },
  target: 'node',
  module: {
    rules: [
      // all files with a `.ts` or `.tsx` extension will be handled by `ts-loader`
      { test: /\.tsx?$/, loader: 'ts-loader' },
    ],
  },
};
```

* What stacktrace or error message from your provider did you see?

Lambda fails to run with the following error message:

```
Unable to import module 'src/handler': Error
at Function.Module._resolveFilename (module.js:547:15)
```

But, as far as I know, this error message is misleading and means that one of the dependencies was not found (which is the case).

## Additional Data

* ***Serverless-Webpack Version you're using***:

```js
    "serverless-webpack": "^5.2.0"
```

* ***Webpack version you're using***:

```js
    "webpack": "^4.29.6",
    "webpack-node-externals": "^1.7.2"
```

* ***Serverless Framework Version you're using***:
1.41.1

* ***Operating System***:
macOS 10.14.4
