### ISSUE TITLE
support bundling multiple packages

### ISSUE THREAD

**Issue by stevemao** [serverless-heaven/serverless-webpack#503]
I have a mono repo like this

packages
  - package-1
  - package-2

I have a module in package-2 that requires some module in package-1 like this:

`require('../package-1/index')`

And I'd like to exclude both node_modules of package-1 and package-2 when I build package-2. 

I can externalise both with webpack:

```js
// webpack.config.js
var nodeExternals = require('webpack-node-externals')

module.exports = {
  // we use webpack-node-externals to excludes all node deps.
  // You can manually set the externals too.
  externals: [nodeExternals(), nodeExternals({modulesDir: '../package-1/node_modules'})],
}
```

Would be good if I could do something like this:

```yml
custom:
  webpack:
    includeModules:
      packagePath: 
        - './package.json'
        - '../package-1/package.json'
```

**Comment by olup** [comment]
Hey any news about this ? Webpack outputs a package.json with empty dependencies numbers when they are from my aliased package with it's own `package.json`. Figured I need a way to tell webpack to look for version number in both local and linked `package.json`. Can we do this with the plugin ?

**Comment by sthuber90** [comment]
Couldn't get it to work, so I switched to serverless-jetpack and serverless-scriptable-plugin

**Comment by olup** [comment]
Too bad, what was wrong ? Did you try to PR an implementation in `packExternalMoules.js` ? Do you have an example repo of your configuration serverless-jetpack and serverless-scriptable-plugin ?

**Comment by sthuber90** [comment]
I also had the problem that not the right dependencies were package into during deployment. Furthermore the `yarn.lock`file was ignored. I'm too unexperienced on the serverless plugins to be able to file a PR. And honestly I was also just looking for something that works out of the box or with not much configuration and the [serverless-jetpack-plugin](https://github.com/FormidableLabs/serverless-jetpack), in combination with the [serverless-scriptable-plugin](https://github.com/weixu365/serverless-scriptable-plugin) solved it for me.

All I had to do there, was to change my serverless.ym files (I have on serverless.yml in each package):
``` yml
custom:
  scriptHooks:
    # These are all the places that jetpack could be invoked that would
    # ensure the TS files are built right before jetpack kicks in.
    # Hooks Cheat Sheet: https://gist.github.com/HyperBrain/50d38027a8f57778d5b0f135d80ea406#file-lifecycle-cheat-sheet-md
    before:invoke:local:invoke: yarn run build
    before:package:createDeploymentArtifacts: yarn run build
    before:package:function:package: yarn run build
    before:jetpack:package:package: yarn run build
  jetpack:
    base: "../.."
    preInclude:
      - "!**" # Start with absolutely nothing (typical in monorepo scenario)

package:
  individually: true
```

And `yarn build` just runs `tsc -b tsconfig.json`
