### ISSUE TITLE
Reduce bundle size by removing unnecessary files from node_modules

### ISSUE THREAD

**Issue by mcongy** [serverless-heaven/serverless-webpack#519]
# This is a Feature Proposal

## Description

* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

node_modules include a lot of unnecessary files (license files, test files, CI/CD config files, build config files etc.).
These files are absolutely useless and are not needed runtime.
They increase the bundle size, the time it takes to zip bundles and upload them to S3.
We can save a significant amount of time (and even money to some degree) by removing them.
Yarn has a functionality called "autoclean". It removes files specified by a glob pattern from node_modules https://yarnpkg.com/en/docs/cli/autoclean
We could use yarn's autoclean funcionality or remove the unnecessary files ourselves.

I think this should be a configurable option. 
Maybe we could allow executing an "autoclean" script after packager install it's depencencies? Maybe here?
https://github.com/serverless-heaven/serverless-webpack/blob/21393845fb173a6f806b0bc2bee0be7daf0adc86/lib/packExternalModules.js#L329-L332

* If there is additional config how would it loo

Maybe something like this?
```yml
webpack:
  packagerOptions:
    postInstallScripts:
      - yarn autoclean --force
```

**Comment by HyperBrain** [comment]
Hi @mcongy ,

did you try 
```
custom:
  webpack:
    packagerOptions:
      scripts:
        - yarn autoclean --force
```

The scripts option is made especially to execute vustom scripts after installation of the node modules

**Comment by mcongy** [comment]
Hi @HyperBrain 

Sorry for reacting so late.

I didn't realize I can specify post-installation script. It could work very well.
The problem is, in order to be able to "yarn autoclean", the .yarnclean file has to be in current working directory.
In case of packaging individually, I'd have to copy the .yarnclean file into all the folders I want to autoclean.

Do you have an idea, what would be the best solution to doing this?
Or maybe the support for this could be implemented in the plugin itself?

Thanks!

**Comment by jabas06** [comment]
This worked for me:

```yml
  webpack:
    webpackConfig: "webpack.config.js"
    packager: "yarn"
    packagerOptions:
      scripts:
        - yarn autoclean --init
        - yarn autoclean --force
    includeModules: true
```
> Hi @mcongy ,
> 
> did you try
> 
> ```
> custom:
>   webpack:
>     packagerOptions:
>       scripts:
>         - yarn autoclean --force
> ```
> 
> The scripts option is made especially to execute vustom scripts after installation of the node modules
