### ISSUE TITLE
Using this plugin causes bundle size expensive

### ISSUE THREAD

**Issue by Hwan-seok** [serverless-heaven/serverless-webpack#555]
# This is a ( Question )

## Description
I used `serverless-plugin-typescript` and `serverless-plugin-optimize` previously.
But it is hard to debug from log. So I'm in progress of migrate my project from above to `serverless-webpack`. And I successfully migrated to this but the deploy time and bundle size is too expensive than before...

I measured time and bundle size and the result is as follows
- using `typescript and optimize` : 3min 30 sec, 2.5MB
- using this plugin : 5min + a, 11MB

I assume that node_modules size affected to this because former one's output is only `main.js`
but this plugin's output bundle has a lot as follows
```
.webpack
  └ service
      └ src
      └ node_modules
           └ ...packages a lot
  └ dependency
      └ package.json
      └ node_modules
           └ ...packages a lot

```

my script is as follows
`sls deploy function -s stage --function main --verbose`

Is this normal?
Or, How can I improve mine?

For reference:
#### serverless.yaml
```
service:
  name: WHATEVER

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-2
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${self:provider.stage}
    NODE_ENV: ${self:provider.stage}

plugins:
  - serverless-webpack
  - serverless-offline

package:
  include:
    - env
  individually: false
  excludeDevDependencies: false

custom:
  webpack: 
    webpackConfig: './webpack.lambda.config.js'
    packager: 'npm'
    includeModules:
      forceExclude:
        - aws-sdk
        - '@types/node'
        - '@types/bluebird'
        - '@types/validator'
      forceInclude:
        - mysql2
    keepOutputDirectory: true

functions:
  main: 
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /
          cors: true
      - http:
          method: any
          path: /{any+}
          cors: true

```
#### webpack.lambda.config.js
```json
{
  target: 'node',
  mode: 'none',
  entry: serverlessWebpack.lib.entries,
  node: {
    __dirname: false,
    __filename: false,
  },
  externals: [nodeExternals()],
  module: {
    rules: [
      {
        test: /.tsx?$/,
        exclude: /node_modules/,
        options: {
          transpileOnly: true,
        },
        loader: 'ts-loader',
      },
    ],
  },
  resolve: {
    extensions: ['.tsx', '.ts', '.js'],
  },
  output: {
    libraryTarget: 'commonjs2',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js',
  },
  devtool:'inline-cheap-module-source-map',
  optimization: {
    minimize: false,
    nodeEnv: false,
  },
  plugins: [
    new ForkTsCheckerWebpackPlugin({ eslint: true }),
    new CopyWebpackPlugin([{ from: 'env/', to: 'env/' }]),
  ],
};
```
## Additional Data

* ***Serverless-Webpack Version you're using***:
```
    "serverless-offline": "^5.12.1",
    "serverless-plugin-optimize": "^4.1.3-rc.1",
    "serverless-plugin-typescript": "^1.1.7",
    "serverless-webpack": "^5.3.1",
```
* ***Webpack version you're : 4.41.5
* ***Serverless Framework Version you're using***: 
```
Framework Core: 1.63.0
Plugin: 3.3.0
SDK: 2.3.0
Components Core: 1.1.2
Components CLI: 1.4.0
```
* ***Operating System***: windows 10
* ***Stack Trace (if available)***:
