### ISSUE TITLE
Issue with google-cloud-serverless: The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by paladiy** [serverless-heaven/serverless-webpack#604]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?

While trying to use `serverless-bundle` (that uses `serverless-webpack`) on the google env with google-cloud-serverless we've faced an issue with handler configuration which caused error: `The "path" argument must be of type string. Received type undefined`

The problem happened in this part of validation logic https://github.com/serverless-heaven/serverless-webpack/blob/master/lib/validate.js#L186 

It seems like it expects aws-like format but google asks to avoid having file name and path in the handler definition. Link to [documentation](https://www.serverless.com/framework/docs/providers/google/guide/functions#handler)

* What did you expect should have happened?

It seems like validation part should be different per provider (in this case google)
or maybe if you know workaround that will help to resolve this problem?

* What was the config you used?

```
service: service-name

provider:
  name: google
  runtime: nodejs10
  timeout: 90s
  memorySize: 1024
  stage: stable
  project: ${file(~/.gcloud/anything-importer.json):project_id}
  credentials: ~/.gcloud/anything-importer.json

plugins:
  - serverless-bundle
  - serverless-google-cloudfunctions

functions:
  importer:
    handler: importGCF
    events:
      - http: path
  importer-pubsub:
    timeout: 300s
    handler: importPubsub
    events:
      - event:
          eventType: providers/cloud.pubsub/eventTypes/topic.publish
          resource: 'projects/${self:provider.project, ""}/topics/importPubsub'


package:
  individually: true

``` 

* What stacktrace or error message from your provider did you see?

```
  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
      at assertPath (path.js:39:11)
      at Object.relative (path.js:1171:5)
      at _.map.funcName (project-path/src/node_modules/serverless-webpack/lib/validate.js:188:36)
      at arrayMap (project-path/src/node_modules/lodash/lodash.js:639:23)
      at Function.map (project-path/src/node_modules/lodash/lodash.js:9580:14)
      at processConfig (project-path/src/node_modules/serverless-webpack/lib/validate.js:183:37)
      at ServerlessPlugin.validate (project-path/src/node_modules/serverless-webpack/lib/validate.js:234:14)
      at ServerlessPlugin.tryCatcher (project-path/src/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (project-path/src/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (project-path/src/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromiseCtx (project-path/src/node_modules/bluebird/js/release/promise.js:641:10)
      at _drainQueueStep (project-path/src/node_modules/bluebird/js/release/async.js:97:12)
      at _drainQueue (project-path/src/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (project-path/src/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (project-path/src/node_modules/bluebird/js/release/async.js:15:14)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
      at process.topLevelDomainCallback (domain.js:121:23)

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              10.14.1
     Framework Version:         1.75.1
     Plugin Version:            3.6.16
     SDK Version:               2.3.1
     Components Version:        2.32.0

error Command failed with exit code 1.
```

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.3.1
* ***Webpack version you're using***: 4.35.3
* ***Serverless Framework Version you're using***: 1.75.1
