### ISSUE TITLE
Console throws "Require is not defined" err when loading sls-webpack bundle with sls-offline

### ISSUE THREAD

**Issue by mepc36** [serverless-heaven/serverless-webpack#611]
# This is a Bug Report:

## Description

For bug reports:
* What went wrong?

When my index.html tries to load the bundle with a <src/> tag, the browser's console logs the following error:

```
lambda.js:4 Uncaught ReferenceError: require is not defined
    at lambda.js:4
```

* What did you expect should have happened?

The browser to load the bundle.

* What was the config you used?
`webpack.config.js`:
```
const slsw = require('serverless-webpack');
const path = require('path');
const webpack = require('webpack')
const CopyWebpackPlugin = require('copy-webpack-plugin');
const nodeExternals = require('webpack-node-externals')

module.exports = (() => {
  const {
    NODE_ENV,
    AUTH0_SPA_CLIENT_ID,
    AUTH0_DOMAIN,
    AUTH0_AUDIENCE_FRONT_END,
  } = slsw.lib.serverless.service.provider.environment

  return {
    mode: 'development',
    entry: slsw.lib.entries,
    // target: 'node',
    output: {
      libraryTarget: 'commonjs',
      path: `${__dirname}/.webpack`,
      filename: 'lambda.js', // this should match the first part of function handler in serverless.yml
    },
    // node: {
    //   __dirname: false // disables webpack from changing what __dirname does
    // },
    module: {
      rules: [
        {
          test: /\.wasm$/,
          loaders: ['wasm-loader']
        },
        {
          test: /\.worker\.js$/,
          use: { loader: 'worker-loader' }
        },
        {
          test: /\.(js|jsx)$/,
          exclude: /node_modules/,
          use: {
            loader: 'babel-loader',
          },
        },
        {
          test: /\.css$/,
          use: [
            'style-loader',
            'css-loader'
          ]
        },
        {
          test: /\.(woff(2)?|ttf|eot|svg)(\?v=\d+\.\d+\.\d+)?$/,
          use: [
            {
              loader: 'file-loader',
              options: {
                name: '[name].[ext]',
                outputPath: 'fonts/'
              }
            }
          ]
        }
      ],
    },
    resolve: {
      extensions: ['.js', '.jsx'],
      alias: {
        '@client': path.resolve(__dirname, './src/client/'),
        '@src': path.resolve(__dirname, './src/'),
        '@lib': path.resolve(__dirname, './src/lib/'),
        '@components': path.resolve(__dirname, './src/client/components/')
      }
    },
    plugins: [
      new webpack.DefinePlugin({
        NODE_ENV: JSON.stringify(NODE_ENV),
        AUTH0_SPA_CLIENT_ID: JSON.stringify(AUTH0_SPA_CLIENT_ID),
        AUTH0_DOMAIN: JSON.stringify(AUTH0_DOMAIN),
        AUTH0_AUDIENCE_FRONT_END: JSON.stringify(AUTH0_AUDIENCE_FRONT_END),
      }),
      new CopyWebpackPlugin({
        patterns: [
          { from: './index.html', to: './' },
        ],
      }),
      new CopyWebpackPlugin({
        patterns: [
          { from: './ffmpeg', to: './' },
        ],
      }),
      new webpack.DefinePlugin({ 'global.GENTLY': false }),
    ],
    node: {
      fs: 'empty'
    }
  }
})();
```
`serverless.yml`:
```
service: rapbot-sls

provider:
  name: aws
  runtime: nodejs12.x
  stage: 'prod'
  environment:
    AUTH0_AUDIENCE: ${ssm:AUTH0_AUDIENCE~true}
    AUTH0_DOMAIN: ${ssm:AUTH0_DOMAIN~true}
    AUTH0_GET_MGMT_TOKEN_URL: ${ssm:AUTH0_GET_MGMT_TOKEN_URL~true}
    AUTH0_GET_USER_URL: ${ssm:AUTH0_GET_USER_URL~true}
    AUTH0_GRANT_TYPE: ${ssm:AUTH0_GRANT_TYPE~true}
    AUTH0_SPA_CLIENT_ID: ${ssm:AUTH0_SPA_CLIENT_ID~true}
    AmazonWSAccessKeyId: ${ssm:AmazonWSAccessKeyId~true}
    AmazonWSSecretKey: ${ssm:AmazonWSSecretKey~true}
    M2M_CLIENT_ID: ${ssm:M2M_CLIENT_ID~true}
    M2M_CLIENT_SECRET: ${ssm:M2M_CLIENT_SECRET~true}
    OXFORD_LAMBDA_API_KEY: ${ssm:OXFORD_LAMBDA_API_KEY~true}
    OXFORD_LAMBDA_URL: ${ssm:OXFORD_LAMBDA_URL~true}
    TWTR_API_KEY: ${ssm:TWTR_API_KEY~true}
    TWTR_API_SECRET_KEY: ${ssm:TWTR_API_SECRET_KEY~true}
    app_id: ${ssm:app_id~true}
    rapBotUserKey: ${ssm:rapBotUserKey~true}
    rapBotAppID: ${ssm:rapBotAppID~true}
    app_key: ${ssm:app_key~true}
    NODE_ENV: 'development'

plugins:
  - serverless-offline
  - serverless-webpack

# package:
# exclude:
# - src/**
# include:
# - src/function/handler.js

custom:
  webpack:
    webpackConfig: 'webpack.config.js' # Name of webpack configuration file
    includeModules: true # Node modules configuration for packaging
    packager: 'npm' # Packager that will be used to package your external modules
    excludeFiles: '' # Provide a glob for files to ignore
  webpackIncludeModules:
    packagePath: './package.json'

functions:
  rapbot-lambda:
    handler: lambda.handler
    events:
      - http:
          path: /
          method: ANY
      - http: 'ANY {proxy+}'

```
* What stacktrace or error message from your provider did you see?

```
lambda.js:4 Uncaught ReferenceError: require is not defined
    at lambda.js:4
```

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

N/A.

* If there is additional config how would it look

Similar or dependent issue(s):
* None found.

## Additional Data

* ***Serverless-Webpack Version you're using***:

"serverless-webpack": "^5.3.2",

* ***Webpack version you're using***:

"webpack": "^4.43.0",

* ***Serverless Framework Version you're using***:

* ***Operating System***:

macOS Mojave, version 10.14.4

* ***Stack Trace (if available)***:

This is the output of my start-up script:

```
Martins-MacBook-Pro-3:dist martinconnor$ sls offline start
Serverless: Legacy configuration detected. Consider to use "custom.webpack" as object (see README).
Serverless: Bundling with Webpack...
Time: 8130ms
Built at: 07/23/2020 11:42:49 AM
     Asset       Size  Chunks             Chunk Names
    ffmpeg   71.7 MiB          [emitted]  
index.html  337 bytes          [emitted]  
 lambda.js     14 MiB  lambda  [emitted]  lambda
Entrypoint lambda = lambda.js
[../node_modules/ffmpeg/index.js] 41 bytes {lambda} [built]
[../node_modules/ffmpeg/lib/ffmpeg.js] 9.13 KiB {lambda} [built]
[./index.js] 24.2 KiB {lambda} [built]
[./lambda.js] 2.05 KiB {lambda} [built]
[./node_modules/aws-serverless-express/index.js] 643 bytes {lambda} [built]
[./node_modules/aws-serverless-express/middleware.js] 648 bytes {lambda} [built]
[./node_modules/aws-serverless-express/src/index.js] 8.9 KiB {lambda} [built]
[./node_modules/axios/index.js] 40 bytes {lambda} [built]
[./node_modules/body-parser/index.js] 2.59 KiB {lambda} [built]
[./node_modules/cookie-parser/index.js] 3.32 KiB {lambda} [built]
[./node_modules/cors/lib/index.js] 6.47 KiB {lambda} [built]
[./node_modules/dynamodb-data-types/lib/dynamodb-data-types.js] 272 bytes {lambda} [built]
[./src/database/db.js] 4.69 KiB {lambda} [built]
[./src/lib/ffmpeg/ffmpeg.js] 40 bytes {lambda} [built]
[child_process] external "child_process" 42 bytes {lambda} [built]
    + 1662 hidden modules

WARNING in ./node_modules/require_optional/index.js 82:18-42
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/mongodb/lib/core/utils.js
 @ ./node_modules/mongodb/lib/operations/list_indexes.js
 @ ./node_modules/mongodb/lib/collection.js
 @ ./node_modules/mongodb/index.js
 @ ./src/database/db.js
 @ ./lambda.js

WARNING in ./node_modules/require_optional/index.js 90:20-44
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/mongodb/lib/core/utils.js
 @ ./node_modules/mongodb/lib/operations/list_indexes.js
 @ ./node_modules/mongodb/lib/collection.js
 @ ./node_modules/mongodb/index.js
 @ ./src/database/db.js
 @ ./lambda.js

WARNING in ./node_modules/require_optional/index.js 97:35-67
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/mongodb/lib/core/utils.js
 @ ./node_modules/mongodb/lib/operations/list_indexes.js
 @ ./node_modules/mongodb/lib/collection.js
 @ ./node_modules/mongodb/index.js
 @ ./src/database/db.js
 @ ./lambda.js

WARNING in ./node_modules/express/lib/view.js 81:13-25
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/express/lib/application.js
 @ ./node_modules/express/lib/express.js
 @ ./node_modules/express/index.js
 @ ./index.js
 @ ./lambda.js

WARNING in ./node_modules/mongodb/lib/operations/connect.js
Module not found: Error: Can't resolve 'mongodb-client-encryption' in '/Users/martinconnor/Desktop/rapbot-lambda/dist/node_modules/mongodb/lib/operations'
 @ ./node_modules/mongodb/lib/operations/connect.js
 @ ./node_modules/mongodb/lib/mongo_client.js
 @ ./node_modules/mongodb/index.js
 @ ./src/database/db.js
 @ ./lambda.js
Serverless: Watching for changes...
offline: Starting Offline: prod/us-east-1.
offline: Offline [http for lambda] listening on http://localhost:3002

   ┌─────────────────────────────────────────────────────────────────────────────────┐
   │                                                                                 │
   │   ANY | http://localhost:3000/prod                                              │
   │   POST | http://localhost:3000/2015-03-31/functions/rapbot-lambda/invocations   │
   │   ANY | http://localhost:3000/prod/{proxy*}                                     │
   │   POST | http://localhost:3000/2015-03-31/functions/rapbot-lambda/invocations   │
   │                                                                                 │
   └─────────────────────────────────────────────────────────────────────────────────┘

offline: [HTTP] server ready: http://localhost:3000 🚀
offline: 
offline: Enter "rp" to replay the last request
```
