### ISSUE TITLE
No external modules needed - caused due to ES6 module imports with webpack 5.4.0

### ISSUE THREAD

**Issue by dpkshrma** [serverless-heaven/serverless-webpack#656]
# Bug Report

## Description

* What went wrong?

Node modules are not auto-packing as expected. Please check the following repository which helps reproduce this issue - https://github.com/dpkshrma/sls-webpack-peer-dep-issue

According to the documentation, the below configuration should allow to selectively pack only the imported modules:
```js
// webpack.config.js
var nodeExternals = require('webpack-node-externals')

module.exports = {
  // we use webpack-node-externals to excludes all node deps.
  // You can manually set the externals too.
  externals: [nodeExternals()],
}
```
```yaml
# serverless.yml
custom:
  webpack:
    includeModules: true # enable auto-packing of external modules
```
But, with the peer dependency webpack": "^5.4.0, no npm modules are packaged in the artifacts:

![image](https://user-images.githubusercontent.com/7024976/98270122-8de37300-1fb4-11eb-92d2-6aa7c8561436.png)

With peer dependency webpack": "^4.5.1, it works as expected:

![image](https://user-images.githubusercontent.com/7024976/98270163-989e0800-1fb4-11eb-9848-f2206b8fae35.png)

* What did you expect should have happened?
Node modules should have been auto-packed with webpack version 5.4.0

* What was the config you used?
```yaml
service: sls-webpack-peer-dep-issue

provider:
  name: aws
  versionFunctions: false
  runtime: nodejs12.x
  region: ap-south-1
  apiGateway:
    shouldStartNameWithService: true

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules: true
    packager: "yarn"

functions:
  app:
    handler: index.default
    events:
      - http: ANY /{any+}
```

* What stacktrace or error message from your provider did you see?
```bash
$ sls package
Serverless: Bundling with Webpack...
asset index.js 838 bytes [emitted] [minimized] (name: index)
runtime modules 931 bytes 4 modules
orphan modules 126 bytes [orphan] 3 modules
./index.js + 3 modules 387 bytes [not cacheable] [built] [code generated]
webpack compiled successfully in 1108 ms
Serverless: No external modules needed
(node:15690) [DEP_WEBPACK_CHUNK_MODULES_ITERABLE] DeprecationWarning: Chunk.modulesIterable: Use new ChunkGraph API
(Use `node --trace-deprecation ...` to show where the warning was created)
Serverless: Packaging service...
✨  Done in 9.06s.
```

Similar or dependent issue(s):
* #483 

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.3.5
* ***Webpack version you're using***: 5.4.0
* ***Serverless Framework Version you're using***: 2.10.0
* ***Operating System***: MacOS
* ***Stack Trace (if available)***:
