### ISSUE TITLE
Packaging bug when using nodejs based custom runtime 

### ISSUE THREAD

**Issue by MatteoGioioso** [serverless-heaven/serverless-webpack#664]
# This is a Bug

## Description

I am trying to have a custom runtime for one of my lambda function. However when I specify `runtime: provided` webpack is not packaging my function as expected. Instead is packaging the whole project including all the other functions.
If my runtime is not provided (just standard nodejs) then the packaging is correct.
Without webpack plugin it works fine as well.

I have a repro case here: https://github.com/MatteoGioioso/serverless-webpack-bug

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.3.4
* ***Webpack version you're using***: 4.29.6
* ***Serverless Framework Version you're using***: 
```
Framework Core: 1.77.1
Plugin: 3.6.18
SDK: 2.3.1
Components: 2.33.2
```

## Webpack configuration

```

const path = require('path');
const nodeExternals = require('webpack-node-externals');
const slsw = require('serverless-webpack');

module.exports = {
  entry: slsw.lib.entries,
  target: 'node',
  devtool: 'source-map',

  externals: [nodeExternals()],
  module: {
    rules: [
      {
        test: /\.js$/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env'],
          },
        },
        include: __dirname,
        exclude: /node_modules/,
      },
    ],
  },
  output: {
    libraryTarget: 'commonjs2',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js',
    sourceMapFilename: '[file].map',
  },
};

```

### Serverless.yaml simplified

```
service: sls-webpack-bug

provider:
  name: aws
  runtime: nodejs12.x

custom:
  webpack:
    webpackConfig: ./webpack.config.js

package:
  individually: true

plugins:
  - serverless-webpack

functions:
  exampleFunction:
    memorySize: 1024
    timeout: 30
    handler: services/myService/handler.default
    runtime: provided

  exampleFunction2:
    memorySize: 1024
    timeout: 30
    handler: services/anotherService/myHandler.default

```

If I have time I will make a repro case, but I think that should be it for the time being.

PS: **The custom runtime is nodejs in this case**

Thanks

**Comment by MatteoGioioso** [comment]
Ok, I have manage to reproduce it. https://github.com/MatteoGioioso/serverless-webpack-bug
So if `runtime: provided` is passed than the webpack plugin won't work as expected packaging the whole project

**Comment by MatteoGioioso** [comment]
Ok, this is not really a bug: https://github.com/serverless-heaven/serverless-webpack/blob/69dfc3f502ee3a080863d7c1e1a94b996f532c5e/lib/validate.js#L104

You just do not allow any other runtime other than `node`, and this is perfectly understandable, however in my case I am using a custom runtime which is still nodejs base.

So this will turn into a question. How can I include in the serverless-webpack plugin my function with custom runtime?

Sorry for the monologue =)

**Comment by MatteoGioioso** [comment]
Can we have this as a feature? If there is no other workaround of course.

This is the proposed change, not sure you will like it or not.

We add an additional property to allow a custom runtime only if the user set this to `true`

```
  exampleFunction:
    memorySize: 1024
    timeout: 30
    handler: services/myService/handler.default
    runtime: provided
    webpackAllowCustomRuntime: true // whatever name you guys want
```

And then add another check:

```
if (runtime === 'provided' && loadedFunc.webpackAllowCustomRuntime) {
        const entry = getEntryForFunction.call(this, functions[index], loadedFunc);
        _.merge(entries, entry);
}
```

Let me know what you think, on my fork this is already done and tested.
