### ISSUE TITLE
Having handler file anywhere but root fails

### ISSUE THREAD

**Issue by Cmdv** [serverless-heaven/serverless-webpack#839]
# This is a Bug Report

## Description
I tend to have my handler files in a folder off root eg: `/handlers/xx.js`
When using this format with serverless-webpack would create an error:
```
Cannot find module  `/path/to/project/dist/service/handlers/handlerfile.js`
```
`dist/` being my output location for my bundling.
`handlers/` being the location of my handlers

But if I take my handlers out of the `handlers/` and put them same level as both my `serverless.yml` & `webpack.config.js`. Then all is honky dory 🕺  

## Additional Data

* ***Serverless-Webpack Version you're using***: Latest
* ***Webpack version you're using***: Latest
* ***Serverless Framework Version you're using***: Latest
* ***Operating System***: MacOS
* ***Stack Trace (if available)***:

**Comment by j0k3r** [comment]
Could you share a minimal config with `serverless.yml` & `webpack.config.js` ? So I can try to debug it and fix it. Thanks 🙏

**Comment by Cmdv** [comment]
@j0k3r yeah sure no problems

```
...
functions:
  screenshot:
    handler: handlers/screenshot.handler
    environment:
      SERVERLESS_STAGE: ${opt:stage}
...  
```

```
const path = require('path');
const webpack = require('webpack');
const nodeExternals = require('webpack-node-externals');
const slsw = require('serverless-webpack');

module.exports = {
  entry: {
      screenshot: "./handlers/screenshot.js"
  },
  mode: slsw.lib.webpack.isLocal ? "development" : "production",
  optimization: {
    // minimize: false
  },
  output: {
    libraryTarget: 'commonjs',
    path: path.resolve(__dirname, "dist"),
    filename: '[name].js'
  },
  target: 'node',
  plugins: [
    new webpack.ProvidePlugin({'XMLHttpRequest': 'xhr2'})
  ],
  module: {
    rules: [
      {
        test: /\.purs$/,
        use: [
          {
            loader: "purs-loader",
            options: {
              spago: true,
            }
          }
        ]
      },
    ]
  },
  resolve: {
    modules: [ 'node_modules' ],
    extensions: [".js", ".purs"]
  },
  externals: [nodeExternals({
    allowlist: ['XMLHttpRequest']
  })]
};
```

but if I remove `/handlers/` put the file inside the root it all works.

**Comment by j0k3r** [comment]
I've created a minimal repro too and I do not have errors.

```yaml
service: test

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  versionFunctions: false

plugins:
  - serverless-webpack

functions:
  hello:
    handler: handlers/handler.hello

custom:
  webpack:
    packager: yarn
    keepOutputDirectory: true
```

```js
const path = require('path');
const slsw = require('serverless-webpack');

module.exports = {
  entry: {
    hello: "./handlers/handler.js"
  },
  mode: slsw.lib.webpack.isLocal ? "development" : "production",
  target: 'node',
  module: {},
  output: {
    libraryTarget: 'commonjs',
    path: path.resolve(__dirname, "dist"),
    filename: '[name].js'
  },
  resolve: {
    modules: [ 'node_modules' ],
    extensions: [".js"]
  },
};
```

The packaging is ok

```
$ serverless package
Serverless: Bundling with Webpack...
Time: 115ms
Built at: 2021-06-11 10:29:49
   Asset      Size  Chunks             Chunk Names
hello.js  1.05 KiB       0  [emitted]  hello
Entrypoint hello = hello.js
[0] ./handlers/handler.js 123 bytes {0} [built]
Serverless: Copying existing artifacts...
Serverless: Packaging service...
$
```
