### ISSUE TITLE
Runtime.HandlerNotFound .webpack/service/src/index.handle is undefined or not exported

### ISSUE THREAD

**Issue by aishwarya257** [serverless-heaven/serverless-webpack#892]
# This is a Bug Report)

I am getting HandlerNotFound error. The zipped package has a `src` folder and within it there's an index.js file. But despite that I am getting this error, and I am getting this only after upgrading serverless, serverless-webpack and webpack.

Current versions:

    "serverless": "2.46.0",
    "serverless-webpack": "5.5.1",
    "webpack": "5.38.1"

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?
```
2021-06-23T10:02:32.643Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Runtime.HandlerNotFound",
    "errorMessage": ".webpack/service/src/index.handle is undefined or not exported",
    "stack": [
        "Runtime.HandlerNotFound: .webpack/service/src/index.handle is undefined or not exported",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:144:11)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:1068:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)",
        "    at Module.load (internal/modules/cjs/loader.js:933:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:774:14)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}
```
For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issue(s):

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.5.1
* ***Webpack version you're using***: 5.38.1
* ***Serverless Framework Version you're using***: 2.46.0
* ***Operating System***:
* ***Stack Trace (if available)***:

**Comment by j0k3r** [comment]
Could you share more information? Like your serverless.yml, the tree structure of your project, etc..

**Comment by aishwarya257** [comment]
Yes I can

serverless.yml

```
plugins:
  - serverless-webpack
  - serverless-apigw-binary
  - serverless-localstack

custom:
  apigwBinary:
    types:
      - '*/*'
  imageBucketName: <value>
  pdfBucketName: <value>
  domainName: <value>
  secretName: <value>
  defaultStage: local
  localstack:
    stages:
      - local
    host: http://localhost
    lambda:
      mountCode: True
    docker:
      sudo: True
  webpack:
    packager: 'yarn'
    keepOutputDirectory: true
    includeModules:
      forceExclude:
        - aws-sdk
      forceInclude:
        - sharp
  ```

And the project structure is

root -> src -> index.ts

webpack.config.js

```
const path = require('path');
const slsw = require('serverless-webpack');

module.exports = {
  entry: slsw.lib.entries,
  resolve: {
    extensions: ['.js', '.jsx', '.json', '.ts', '.tsx'],
  },
  output: {
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js',
  },
  externals: {
    sharp: 'commonjs sharp',
  },
  target: 'node',
  module: {
    rules: [{ test: /\.ts(x?)$/, loader: 'ts-loader' }],
  },
  mode: process.env.IS_OFFLINE ? 'development' : 'production',
};
```
