### ISSUE TITLE
Different machines, different bundle sizes

### ISSUE THREAD

**Issue by gbiagini97** [serverless-heaven/serverless-webpack#983]
# This is a Bug Report 

## Description
I have a serverless service that makes use of puppeteer, and I definitely need webpack to bundle everything and reduce the zip size otherwise I receive this error: `Serverless: Uploading service update-tickers.zip file to S3 (183.59 MB)...`

The point is that two different PCs bundle the same service with two different sizes (~180 MB vs ~50 MB), while I'd expect the same result from both.

My package.json
```json
{
  "name": "update-tickers",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "export-env": "sls export-env",
    "package": "sls package",
    "deploy": "sls deploy && sls export-env",
    "remove": "sls remove"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/core": "^7.14.2",
    "babel-loader": "^8.2.2",
    "serverless": "2.52.1",
    "serverless-export-env": "1.4.4",
    "serverless-plugin-aws-alerts": "^1.7.3",
    "serverless-step-functions": "^2.29.0",
    "serverless-tag-cloud-watch-log-groups": "^1.0.0",
    "serverless-webpack": "^5.5.1",
    "webpack": "^5.47.1",
    "puppeteer": "^10.1.0",
    "webpack-node-externals": "^3.0.0"
  },
  "dependencies": {
    "axios": "^0.21.1",
    "luxon": "^2.0.1",
    "chrome-aws-lambda": "^10.1.0",
    "puppeteer-core": "^10.1.0",
    "puppeteer-extra": "^3.1.18",
    "puppeteer-extra-plugin-stealth": "^2.7.8"
  }
}
```

My serverless.yml plugins and webpack config declaration
```yml
...

plugins:
  - serverless-export-env
  - serverless-step-functions
  - serverless-webpack
  - serverless-tag-cloud-watch-log-groups

provider:
  name: aws
  runtime: nodejs14.x

...

custom: 

  webpack:
    webpackConfig: webpack.config.js
    packager: 'npm'
    individually: true
    includeModules:
      forceExclude:
        - aws-sdk
        - puppeteer

...
```

My webpack.config.js
```js
const slsw = require('serverless-webpack')
const nodeExternals = require('webpack-node-externals')
// const { NormalModuleReplacementPlugin } = require('webpack')

module.exports = {
  entry: slsw.lib.entries,
  // target: 'node',
  // Generate sourcemaps for proper error messages
  devtool: 'source-map',
  // Since 'aws-sdk' is not compatible with webpack,
  // we exclude all node dependencies
  externalsPresets: { node: true },
  externals: [
    nodeExternals(),
    "puppeteer-core",
    "puppeteer-extra",
    "puppeteer-extra-plugin-stealth",
    "chrome-aws-lambda"
  ],
  mode: slsw.lib.webpack.isLocal ? 'development' : 'production',
  optimization: {
    // We do not want to minimize our code.
    minimize: false
  },
  performance: {
    // Turn off size warnings for entry points
    hints: false
  },
  // Run babel on all .js files and skip those in node_modules
  module: {
    rules: [
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: __dirname,
        exclude: /node_modules/
      }
    ]
  },
  plugins: [
    // Ignore knex dynamic required dialects that we don't use
    // new NormalModuleReplacementPlugin(/mssql?|oracle(db)?|sqlite3|pg-(native|query)/, 'noop2')
  ]
}
```

The pc that builds the ~180 MB package has the following configuration:
```
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.15.4
     Framework Version:         2.51.2 (local)
     Plugin Version:            5.4.7
     SDK Version:               4.3.0
     Components Version:        3.17.1
```

Do you guys have any clue about this?
